(async function(){const A=window.RajuAdmin,auth=await A.guard();if(!auth)return;A.bindShell();
const c=A.client, msg=document.getElementById('adminMessage'), show=(t,k='')=>{msg.textContent=t;msg.className='notice '+k;};
const today=new Date();const dayStart=new Date(today);dayStart.setHours(0,0,0,0);const dayEnd=new Date(dayStart);dayEnd.setDate(dayEnd.getDate()+1);
const {data:ins}=await c.from('instructors').select('id,name,active').order('name');const instructors=ins||[];const imap=new Map(instructors.map(x=>[x.id,x]));
const [s,b,p,l]=await Promise.all([
 c.from('student_profiles').select('id,full_name,email,phone,total_course_fee,applying_for,created_at').order('full_name'),
 c.from('bookings').select('id,student_id,requested_start,requested_end,duration_minutes,status,class_fee,assigned_instructor_id,preferred_instructor_id').order('requested_start',{ascending:true}),
 c.from('fee_payments').select('id,student_id,booking_id,amount,paid_on').order('paid_on',{ascending:false}).limit(1000),
 c.from('student_learning_progress').select('student_id,content_key,completed_at')
]);
for(const x of [s,b,p,l])if(x.error){show(x.error.message,'error');return;} const students=s.data||[], bookings=b.data||[], payments=p.data||[], lessons=l.data||[]; const smap=new Map(students.map(x=>[x.id,x]));
const pending=bookings.filter(x=>['pending_payment','payment_recorded'].includes(x.status)); const todayBookings=bookings.filter(x=>{const d=new Date(x.requested_start);return d>=dayStart&&d<dayEnd&&['pending_payment','payment_recorded','approved','completed'].includes(x.status)});
const avg=students.length?Math.round(students.reduce((sum,s)=>{const rows=lessons.filter(x=>x.student_id===s.id&&x.completed_at);return sum+Math.min(100,Math.round(rows.length/25*100));},0)/students.length):0;
document.getElementById('statStudents').textContent=students.length;document.getElementById('statPending').textContent=pending.length;document.getElementById('statToday').textContent=todayBookings.length;document.getElementById('statCollected').textContent=A.money(payments.reduce((x,y)=>x+Number(y.amount||0),0));document.getElementById('statLearning').textContent=avg+'%';document.getElementById('heroPending').textContent=pending.length+' new request'+(pending.length===1?'':'s');document.getElementById('heroToday').textContent=todayBookings.length+' classes today';document.getElementById('heroStudents').textContent=students.length+' students';document.getElementById('sideAdminName').textContent=auth.admin.full_name||auth.admin.email||'Admin';
const inbox=document.getElementById('requestInbox');inbox.innerHTML=pending.slice(0,5).map(x=>{const st=smap.get(x.student_id)||{};const inst=imap.get(x.assigned_instructor_id)||imap.get(x.preferred_instructor_id);return `<div class="inbox-item"><div class="mini-avatar">${A.initials(st.full_name)}</div><div class="inbox-main"><strong>${A.esc(st.full_name||'Student')}</strong><span>${A.dateTime(x.requested_start)} · ${x.duration_minutes/60} hr · ${A.esc(inst?.name||'Instructor not assigned')}</span></div><span class="pill amber">${A.money(x.class_fee)}</span><a class="admin-btn" href="bookings/">Review</a></div>`}).join('')||'<div class="empty-state"><div class="big">✓</div><strong>No new booking requests</strong><p>New student requests will appear here.</p></div>';
const spotlight=document.getElementById('studentSpotlight');spotlight.innerHTML=students.slice(0,6).map(st=>{const done=lessons.filter(x=>x.student_id===st.id&&x.completed_at).length;return `<a class="student-row" href="students/student.html?id=${encodeURIComponent(st.id)}"><div class="mini-avatar">${A.initials(st.full_name)}</div><div class="grow"><strong>${A.esc(st.full_name||'Student')}</strong><small>${A.esc(st.applying_for||'Driving course')} · ${done}/25 lessons</small></div><span>›</span></a>`}).join('')||'<div class="empty-state">No students found.</div>';
const tb=document.getElementById('todayBoard');tb.innerHTML=todayBookings.slice(0,8).map(x=>{const st=smap.get(x.student_id)||{};const inst=imap.get(x.assigned_instructor_id)||imap.get(x.preferred_instructor_id);return `<div class="inbox-item"><div class="mini-avatar">${A.initials(st.full_name)}</div><div class="inbox-main"><strong>${A.esc(st.full_name||'Student')}</strong><span>${new Intl.DateTimeFormat('en-IN',{hour:'numeric',minute:'2-digit'}).format(new Date(x.requested_start))} · ${A.esc(inst?.name||'Unassigned')}</span></div><span class="pill ${x.status==='approved'?'green':x.status.includes('pending')?'amber':''}">${A.esc(x.status.replaceAll('_',' '))}</span></div>`}).join('')||'<div class="empty-state">No classes scheduled today.</div>';
const cb=document.getElementById('capacityBoard');cb.innerHTML=instructors.filter(i=>i.active).map(i=>{const next=todayBookings.find(x=>(x.assigned_instructor_id===i.id)&&new Date(x.requested_end)>new Date());const st=next?smap.get(next.student_id):null;return `<div class="inbox-item"><div class="mini-avatar">🚗</div><div class="inbox-main"><strong>${A.esc(i.name)}</strong><span>${next?`Next: ${A.dateTime(next.requested_start)} · ${A.esc(st?.full_name||'Student')}`:'No class booked right now'}</span></div><span class="pill ${next?'amber':'green'}">${next?'Busy':'Open'}</span></div>`}).join('')||'<div class="empty-state">No active instructors.</div>';
document.getElementById('refreshDashboard').onclick=()=>location.reload();})();
