(async function(){const A=window.RajuAdmin,auth=await A.guard();if(!auth)return;A.bindShell();const c=A.client,root=document.getElementById('profileRoot'),id=new URLSearchParams(location.search).get('id');if(!id){root.innerHTML='<div class="admin-card empty-state">Student ID missing. <a href="./">Back to students</a></div>';return;}
const [s,l,m,b,p,i]=await Promise.all([
 c.from('student_profiles').select('*').eq('id',id).maybeSingle(),
 c.from('student_learning_progress').select('*').eq('student_id',id).order('updated_at',{ascending:false}),
 c.from('student_mock_test_attempts').select('*').eq('student_id',id).order('attempted_at',{ascending:false}),
 c.from('bookings').select('id,requested_start,requested_end,duration_minutes,status,class_fee,assigned_instructor_id,preferred_instructor_id,student_note,admin_note,created_at').eq('student_id',id).order('requested_start',{ascending:false}),
 c.from('fee_payments').select('id,booking_id,amount,paid_on,payment_method,receipt_number,note').eq('student_id',id).order('paid_on',{ascending:false}),
 c.from('instructors').select('id,name')
]);for(const x of [s,l,m,b,p,i])if(x.error){document.getElementById('adminMessage').textContent=x.error.message;document.getElementById('adminMessage').className='notice error';return;}const st=s.data,lessons=l.data||[],mocks=m.data||[],bookings=b.data||[],payments=p.data||[],imap=new Map((i.data||[]).map(x=>[x.id,x.name]));if(!st){root.innerHTML='<div class="admin-card empty-state">Student profile not found.</div>';return;}
const done=lessons.filter(x=>x.completed_at).length, progress=Math.min(100,Math.round(done/25*100)),completed=bookings.filter(x=>x.status==='completed'),hours=bookings.filter(x=>['approved','completed'].includes(x.status)).reduce((a,x)=>a+Number(x.duration_minutes||0)/60,0),paid=payments.reduce((a,x)=>a+Number(x.amount||0),0),best=mocks.reduce((a,x)=>Math.max(a,Number(x.score||0)),0),pending=bookings.filter(x=>['pending_payment','payment_recorded'].includes(x.status)).length;
root.innerHTML=`<div class="admin-page-head"><div><div class="eyebrow">LEARNER PROFILE</div><h1>${A.esc(st.full_name||'Student')}</h1><p>Full training history, progress, class attendance and payment record.</p></div><div class="admin-actions"><a class="admin-btn secondary" href="./">← Student directory</a></div></div>
<section class="admin-card detail-hero"><div class="detail-avatar">${A.initials(st.full_name)}</div><div><h2>${A.esc(st.full_name||'Student')}</h2><p>${A.esc(st.email||'')} ${st.phone?' · '+A.esc(st.phone):''}</p><span class="pill green">${A.esc(st.student_status||'Registered')}</span></div><a class="admin-btn" href="../finance/">Finance</a></section>
<div class="detail-stats"><div class="detail-stat"><span>Learning</span><strong>${progress}%</strong><small>${done}/25 lessons</small></div><div class="detail-stat"><span>Classes completed</span><strong>${completed.length}</strong><small>${hours.toFixed(1)} training hours</small></div><div class="detail-stat"><span>Best mock score</span><strong>${best}%</strong><small>${mocks.length} attempt${mocks.length===1?'':'s'}</small></div><div class="detail-stat"><span>Payments</span><strong>${A.money(paid)}</strong><small>${payments.length} payment${payments.length===1?'':'s'}</small></div></div>
<div class="detail-grid"><section class="admin-card"><div class="card-head"><div><h2>Student details</h2><p>Registration and course information.</p></div></div><div class="card-body"><div class="info-list"><div class="info-item"><small>Applying for</small><strong>${A.esc(st.applying_for||st.license_category||'—')}</strong></div><div class="info-item"><small>Course</small><strong>${A.esc(st.course||'—')}</strong></div><div class="info-item"><small>Date of birth</small><strong>${A.esc(st.date_of_birth||'—')}</strong></div><div class="info-item"><small>Blood group</small><strong>${A.esc(st.blood_group||'—')}</strong></div><div class="info-item"><small>Pincode</small><strong>${A.esc(st.pincode||'—')}</strong></div><div class="info-item"><small>Enrollment</small><strong>${A.esc(st.enrollment_date||'—')}</strong></div><div class="info-item" style="grid-column:1/-1"><small>Address</small><strong>${A.esc(st.address||'—')}</strong></div></div></div></section>
<section class="admin-card"><div class="card-head"><div><h2>Learning progress</h2><p>Lesson completion saved by the student.</p></div><strong>${progress}%</strong></div><div class="card-body"><div class="progress-track" style="height:11px"><i style="width:${progress}%"></i></div><div class="lesson-progress" style="margin-top:18px">${Array.from({length:25},(_,n)=>{const row=lessons.find(x=>String(x.content_key)===('lesson-'+String(n+1).padStart(2,'0')));return `<div class="lesson-progress-row"><span>Lesson ${String(n+1).padStart(2,'0')}</span><div class="progress-track"><i style="width:${row?.completed_at?'100':'0'}%"></i></div><strong>${row?.completed_at?'✓':'—'}</strong></div>`}).join('')}</div></div></section></div>
<section class="admin-card" style="margin-top:18px"><div class="card-head"><div><h2>Mock test performance</h2><p>Latest attempts and scores.</p></div><span class="pill ${best>=80?'green':''}">${best}% best</span></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Attempted</th><th>Score</th><th>Result</th></tr></thead><tbody>${mocks.slice(0,15).map(x=>`<tr><td>${A.dateTime(x.attempted_at)}</td><td><strong>${Number(x.score||0)}%</strong>${x.total_questions?` · ${x.correct_answers||0}/${x.total_questions}`:''}</td><td><span class="pill ${Number(x.score||0)>=80?'green':'amber'}">${Number(x.score||0)>=80?'Strong':'Keep practising'}</span></td></tr>`).join('')||'<tr><td colspan="3">No mock test attempts yet.</td></tr>'}</tbody></table></div></section>
<section class="admin-card" style="margin-top:18px"><div class="card-head"><div><h2>Class history</h2><p>Requested, approved and completed driving classes.</p></div><span class="pill">${pending} new request${pending===1?'':'s'}</span></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Date & time</th><th>Instructor</th><th>Duration</th><th>Fee</th><th>Status</th></tr></thead><tbody>${bookings.map(x=>`<tr><td>${A.dateTime(x.requested_start)}</td><td>${A.esc(imap.get(x.assigned_instructor_id)||imap.get(x.preferred_instructor_id)||'Unassigned')}</td><td>${Number(x.duration_minutes||0)/60} hr</td><td>${A.money(x.class_fee)}</td><td><span class="pill ${x.status==='approved'||x.status==='completed'?'green':x.status==='cancelled'||x.status==='rejected'?'red':'amber'}">${A.esc(x.status.replaceAll('_',' '))}</span></td></tr>`).join('')||'<tr><td colspan="5">No bookings yet.</td></tr>'}</tbody></table></div></section>
<section class="admin-card" style="margin-top:18px"><div class="card-head"><div><h2>Payment history</h2><p>All manual payments recorded for this learner.</p></div><strong>${A.money(paid)}</strong></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Date</th><th>Amount</th><th>Method</th><th>Receipt</th><th>Note</th></tr></thead><tbody>${payments.map(x=>`<tr><td>${A.dateOnly(x.paid_on)}</td><td><strong>${A.money(x.amount)}</strong></td><td>${A.esc(x.payment_method||'—')}</td><td>${A.esc(x.receipt_number||'—')}</td><td>${A.esc(x.note||'—')}</td></tr>`).join('')||'<tr><td colspan="5">No payments yet.</td></tr>'}</tbody></table></div></section>`;
})();
