from pathlib import Path
p=Path('/mnt/data/raju_v17_work/site/defensive-driving-seminar/index.html')
s=p.read_text()
# CSS additions
needle='.empty{padding:22px;border:1px dashed #cbd8e4;border-radius:15px;color:var(--muted)}'
add='''.empty{padding:22px;border:1px dashed #cbd8e4;border-radius:15px;color:var(--muted)}
.manage-card{margin-top:22px;background:#f8fbff;border:1px solid #d7e6f7;border-radius:18px;padding:20px}.manage-card h3{margin:0 0 6px;color:var(--navy)}.manage-grid{display:grid;grid-template-columns:1fr 1fr auto;gap:10px;align-items:end}.manage-grid input{width:100%;padding:12px 13px;border:1px solid #d4e0ea;border-radius:11px;font:inherit}.manage-label{display:grid;gap:6px;font-size:11px;font-weight:900;color:#44586d}.danger{background:#bd2b2b}.secondary{border:1px solid #cbd9e7;background:#fff;color:var(--navy);border-radius:12px;padding:12px 15px;font-weight:900;cursor:pointer}.manage-result{margin-top:14px}.manage-pass{border:1px solid #cbdced;border-radius:14px;padding:15px;background:#fff}.manage-pass-row{display:flex;justify-content:space-between;gap:15px;padding:7px 0;border-bottom:1px solid #edf1f5;font-size:13px}.manage-pass-row:last-child{border-bottom:0}.manage-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:12px}
@media(max-width:560px){.manage-grid{grid-template-columns:1fr}.manage-grid .primary{width:100%}}'''
s=s.replace(needle,add)
# Add manage card after pass
needle2='<div id="pass" class="pass"></div>\n</section>'
insert='''<div id="pass" class="pass"></div>
<div class="manage-card">
<h3>Already registered? Manage your booking</h3>
<p class="muted" style="margin:0 0 12px">Enter your Booking ID and the mobile number used during registration to view or cancel your seminar seat.</p>
<div class="manage-grid">
<label class="manage-label">Booking ID<input id="manageCode" placeholder="RDS-DS-20260926-01" autocomplete="off"></label>
<label class="manage-label">Mobile number<input id="managePhone" inputmode="tel" placeholder="10-digit mobile number" autocomplete="tel"></label>
<button class="primary" id="findBooking">Find my booking</button>
</div><div id="manageNotice" class="notice"></div><div id="manageResult" class="manage-result"></div>
</div>
</section>'''
s=s.replace(needle2,insert)
# Replace renderPass with enhanced version including cancel
old="""function renderPass(p){const date=fmtDate(p.event_date),time=fmtTime(p.start_time)+(p.end_time?' – '+fmtTime(p.end_time):'');$('pass').className='pass open';$('pass').innerHTML=`<div class=\"pass-card\"><div class=\"pass-brand\"><img src=\"../images/raju-logo.png\" alt=\"Raju Driving School\"><strong>RAJU DRIVING SCHOOL</strong></div><div class=\"pass-title\">DEFENSIVE DRIVING SEMINAR</div><div class=\"pass-name\">${esc(p.full_name)}</div><div class=\"pass-code\">Booking ID: ${esc(p.booking_code)}</div><div class=\"summary\"><div class=\"summary-row\"><span>Date</span><strong>${date}</strong></div><div class=\"summary-row\"><span>Time</span><strong>${time}</strong></div><div class=\"summary-row\"><span>Venue</span><strong>${esc(p.venue||'—')}</strong></div></div><div style=\"display:flex;justify-content:space-between;align-items:end;gap:15px\"><div><small class=\"small-note\">Your assigned seat</small><div class=\"seat\">${String(p.seat_number).padStart(2,'0')}</div></div><div id=\"qr\" class=\"qr\"></div></div><p class=\"small-note\">Show this QR code and booking ID at seminar registration. Please keep this pass available on your phone.</p><button class=\"primary print-btn\" onclick=\"window.print()\">Print / Save Entry Pass</button></div>`;new QRCode($('qr'),{text:'RDS-SEMINAR|'+p.booking_code+'|'+p.seat_number,width:180,height:180});$('pass').scrollIntoView({behavior:'smooth'});}"""
new="""function renderPass(p){const date=fmtDate(p.event_date),time=fmtTime(p.start_time)+(p.end_time?' – '+fmtTime(p.end_time):'');$('pass').className='pass open';$('pass').innerHTML=`<div class=\"pass-card\"><div class=\"pass-brand\"><img src=\"../images/raju-logo.png\" alt=\"Raju Driving School\"><strong>RAJU DRIVING SCHOOL</strong></div><div class=\"pass-title\">DEFENSIVE DRIVING SEMINAR</div><div class=\"pass-name\">${esc(p.full_name)}</div><div class=\"pass-code\">Booking ID: ${esc(p.booking_code)}</div><div class=\"summary\"><div class=\"summary-row\"><span>Date</span><strong>${date}</strong></div><div class=\"summary-row\"><span>Time</span><strong>${time}</strong></div><div class=\"summary-row\"><span>Venue</span><strong>${esc(p.venue||'—')}</strong></div></div><div style=\"display:flex;justify-content:space-between;align-items:end;gap:15px\"><div><small class=\"small-note\">Your assigned seat</small><div class=\"seat\">${String(p.seat_number).padStart(2,'0')}</div></div><div id=\"qr\" class=\"qr\"></div></div><p class=\"small-note\">Show this QR code and booking ID at seminar registration. Please keep this pass available on your phone.</p><button class=\"primary print-btn\" onclick=\"window.print()\">Print / Save Entry Pass</button><button class=\"secondary print-btn\" id=\"passCancelBtn\" type=\"button\">Cancel my booking</button></div>`;new QRCode($('qr'),{text:'RDS-SEMINAR|'+p.booking_code+'|'+p.seat_number,width:180,height:180});$('passCancelBtn').onclick=()=>cancelBooking(p.booking_code,p.phone);$('pass').scrollIntoView({behavior:'smooth'});} 
async function cancelBooking(code,phone){if(!confirm('Cancel this seminar booking? Your seat will be released for another participant.'))return;const {data,error}=await db.rpc('cancel_seminar_booking',{p_booking_code:code,p_phone:phone});if(error){notice(error.message.includes('NOT_FOUND')?'Booking not found. Please check the Booking ID and mobile number.':error.message.includes('ALREADY_ATTENDED')?'This booking has already been checked in and cannot be cancelled online.':'Unable to cancel this booking. Please contact Raju Driving School.');return;}$('manageResult').innerHTML='<div class=\"manage-pass\"><strong>Booking cancelled.</strong><p class=\"muted\" style=\"margin:5px 0 0\">Your seat has been released. If you need another seat, you can book again while seats are available.</p></div>';$('pass').className='pass';load();}
function manageNotice(msg,type='error'){const n=$('manageNotice');n.className='notice show '+type;n.textContent=msg;}
$('findBooking').onclick=async()=>{const code=$('manageCode').value.trim().toUpperCase(),phone=$('managePhone').value.replace(/\\D/g,'');if(!code||phone.length!==10)return manageNotice('Please enter your Booking ID and valid 10-digit mobile number.');$('findBooking').disabled=true;$('findBooking').textContent='Searching…';const {data,error}=await db.rpc('lookup_seminar_booking',{p_booking_code:code,p_phone:phone});$('findBooking').disabled=false;$('findBooking').textContent='Find my booking';if(error||!data?.id)return manageNotice('Booking not found. Please check the Booking ID and mobile number.');const p=data;const statusLabel=p.status==='attended'?'Attended':p.status==='cancelled'?'Cancelled':'Confirmed';$('manageResult').innerHTML=`<div class=\"manage-pass\"><div class=\"manage-pass-row\"><span>Participant</span><strong>${esc(p.full_name)}</strong></div><div class=\"manage-pass-row\"><span>Booking ID</span><strong>${esc(p.booking_code)}</strong></div><div class=\"manage-pass-row\"><span>Seat</span><strong>${String(p.seat_number).padStart(2,'0')}</strong></div><div class=\"manage-pass-row\"><span>Status</span><strong>${statusLabel}</strong></div><div class=\"manage-actions\">${p.status==='confirmed'?'<button class=\"primary danger\" id=\"manageCancel\">Cancel booking</button>':''}</div></div>`;if($('manageCancel'))$('manageCancel').onclick=()=>cancelBooking(p.booking_code,p.phone);};"""
if old not in s:
    raise SystemExit('renderPass block not found')
s=s.replace(old,new)
p.write_text(s)

# Admin page: add prominent check-in panel and delete action
ap=Path('/mnt/data/raju_v17_work/site/admin-dashboard/seminars/index.html')
a=ap.read_text()
needle='<section class="admin-card" style="margin-top:20px"><div class="card-head">'
insert='''<section class="admin-card" style="margin-top:20px"><div class="card-head"><div><h2>Venue check-in</h2><p>Quickly find a confirmed participant by Booking ID, mobile or name, then mark them as attended.</p></div><div class="search-bar" style="margin:0;min-width:min(420px,100%)"><input id="checkinSearch" placeholder="Booking ID, mobile or participant name…"></div></div><div class="card-body"><div id="checkinResults" class="inbox-list"><div class="empty-state">Enter a booking ID, mobile or name to check in a participant.</div></div></div></section>
<section class="admin-card" style="margin-top:20px"><div class="card-head">'''
if needle not in a: raise SystemExit('admin insertion point not found')
a=a.replace(needle,insert,1)
# Change table action cancelled to delete, attended can still restore? Keep restore.
old_action="""r.status==='confirmed'?`<button class=\"admin-btn success\" data-attend=\"${r.id}\">Mark attended</button><button class=\"admin-btn danger\" data-cancel=\"${r.id}\" style=\"margin-left:5px\">Cancel</button>`:r.status==='attended'?'<span class=\"pill green\">Checked in</span>':`<button class=\"admin-btn secondary\" data-confirm=\"${r.id}\">Restore</button>`"""
new_action="""r.status==='confirmed'?`<button class=\"admin-btn success\" data-attend=\"${r.id}\">✓ Mark attended</button><button class=\"admin-btn danger\" data-delete=\"${r.id}\" style=\"margin-left:5px\">Delete</button>`:r.status==='attended'?`<button class=\"admin-btn secondary\" data-confirm=\"${r.id}\">Undo attendance</button><button class=\"admin-btn danger\" data-delete=\"${r.id}\" style=\"margin-left:5px\">Delete</button>`:`<button class=\"admin-btn secondary\" data-confirm=\"${r.id}\">Restore</button><button class=\"admin-btn danger\" data-delete=\"${r.id}\" style=\"margin-left:5px\">Delete</button>`"""
if old_action not in a: raise SystemExit('action block not found')
a=a.replace(old_action,new_action)
# Replace bindRegActions + updateReg with richer functions and checkin
start=a.index('function bindRegActions(){')
end=a.index('function openEdit(e){',start)
replacement="""function bindRegActions(){document.querySelectorAll('[data-attend]').forEach(b=>b.onclick=()=>updateReg(b.dataset.attend,{status:'attended',attended_at:new Date().toISOString()}));document.querySelectorAll('[data-confirm]').forEach(b=>b.onclick=()=>updateReg(b.dataset.confirm,{status:'confirmed',cancelled_at:null,attended_at:null}));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteReg(b.dataset.delete));}
async function updateReg(id,patch){const {error}=await db.from('seminar_registrations').update(patch).eq('id',id);if(error)return msg(error.message,'error');toast(patch.status==='attended'?'Participant checked in ✓':'Participant updated');await loadRegs(selectedEvent.id);renderCheckin();}
async function deleteReg(id){const row=(window.currentRegs||[]).find(r=>r.id===id);if(!row)return;if(!confirm(`Permanently delete ${row.full_name} (${row.booking_code})? This releases seat ${String(row.seat_number).padStart(2,'0')} and cannot be undone.`))return;const {error}=await db.from('seminar_registrations').delete().eq('id',id);if(error)return msg(error.message,'error');toast('Booking deleted and seat released');await loadRegs(selectedEvent.id);renderStats();renderCheckin();}
function renderCheckin(){const q=($('checkinSearch').value||'').trim().toLowerCase();const matches=(window.currentRegs||[]).filter(r=>r.status!=='cancelled'&&(!q||[r.booking_code,r.full_name,r.phone,r.email].some(v=>String(v||'').toLowerCase().includes(q)))).slice(0,10);if(!q){$('checkinResults').innerHTML='<div class="empty-state">Enter a booking ID, mobile or name to check in a participant.</div>';return;}$('checkinResults').innerHTML=matches.length?matches.map(r=>`<div class="inbox-item" style="align-items:center"><div class="mini-avatar">${String(r.seat_number).padStart(2,'0')}</div><div class="inbox-main"><strong>${esc(r.full_name)}</strong><span>${esc(r.booking_code)} · ${esc(r.phone)} · Seat ${String(r.seat_number).padStart(2,'0')}</span><span>Status: <b>${esc(r.status)}</b></span></div>${r.status==='confirmed'?`<button class="admin-btn success" data-checkin="${r.id}">✓ Mark attended</button>`:'<span class="pill green">Already attended</span>'}</div>`).join(''):'<div class="empty-state">No matching confirmed participant found.</div>';document.querySelectorAll('[data-checkin]').forEach(b=>b.onclick=()=>updateReg(b.dataset.checkin,{status:'attended',attended_at:new Date().toISOString()}));}
"""
a=a[:start]+replacement+a[end:]
# bind checkin search after search binding
needle3="$('newEvent').onclick=()=>openEdit();$('closeModal').onclick=()=>$('eventModal').classList.remove('open');$('eventModal').onclick=e=>{if(e.target===$('eventModal'))$('eventModal').classList.remove('open')};$('refresh').onclick=loadEvents;$('search').oninput=renderRegs;"
replace3="$('newEvent').onclick=()=>openEdit();$('closeModal').onclick=()=>$('eventModal').classList.remove('open');$('eventModal').onclick=e=>{if(e.target===$('eventModal'))$('eventModal').classList.remove('open')};$('refresh').onclick=loadEvents;$('search').oninput=renderRegs;$('checkinSearch').oninput=renderCheckin;"
if needle3 not in a: raise SystemExit('binding point not found')
a=a.replace(needle3,replace3)
ap.write_text(a)

# SQL add secure public lookup/cancel and make admin direct delete already exists; strengthen functions
sqlp=Path('/mnt/data/raju_v17_work/site/defensive-driving-seminar.sql')
sql=sqlp.read_text()
append='''\n\n-- Public booking management: users can securely look up and cancel their own booking\n-- by providing BOTH the booking ID and the mobile number used at registration.\ncreate or replace function public.lookup_seminar_booking(\n  p_booking_code text, p_phone text\n) returns jsonb\nlanguage plpgsql security definer set search_path=public\nas $$\ndeclare r public.seminar_registrations%rowtype; e public.seminar_events%rowtype;\nbegin\n  select * into r from public.seminar_registrations\n   where booking_code=upper(trim(p_booking_code))\n     and phone=regexp_replace(p_phone,'[^0-9]','','g') limit 1;\n  if not found then raise exception 'NOT_FOUND'; end if;\n  select * into e from public.seminar_events where id=r.event_id;\n  return jsonb_build_object('id',r.id,'booking_code',r.booking_code,'full_name',r.full_name,'phone',r.phone,'email',r.email,'seat_number',r.seat_number,'status',r.status,'registered_at',r.registered_at,'event_id',e.id,'title',e.title,'event_date',e.event_date,'start_time',e.start_time,'end_time',e.end_time,'venue',e.venue);\nend;\n$$;\ngrant execute on function public.lookup_seminar_booking(text,text) to anon,authenticated;\n\ncreate or replace function public.cancel_seminar_booking(\n  p_booking_code text, p_phone text\n) returns jsonb\nlanguage plpgsql security definer set search_path=public\nas $$\ndeclare r public.seminar_registrations%rowtype;\nbegin\n  select * into r from public.seminar_registrations\n   where booking_code=upper(trim(p_booking_code))\n     and phone=regexp_replace(p_phone,'[^0-9]','','g') limit 1 for update;\n  if not found then raise exception 'NOT_FOUND'; end if;\n  if r.status='attended' then raise exception 'ALREADY_ATTENDED'; end if;\n  if r.status='cancelled' then return jsonb_build_object('id',r.id,'status','cancelled','booking_code',r.booking_code); end if;\n  update public.seminar_registrations set status='cancelled',cancelled_at=now() where id=r.id;\n  return jsonb_build_object('id',r.id,'status','cancelled','booking_code',r.booking_code,'seat_number',r.seat_number);\nend;\n$$;\ngrant execute on function public.cancel_seminar_booking(text,text) to anon,authenticated;\n'''
if 'lookup_seminar_booking' not in sql:
    sql += append
sqlp.write_text(sql)
# also copy same SQL into public setup file
Path('/mnt/data/raju_v17_work/site/defensive-driving-seminar/seminar-setup.sql').write_text(sql)
