(()=>{'use strict';
const C=window.RAJU_HPT_CONFIG; const sb=window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey); const $=id=>document.getElementById(id);
let results=[],videos=[],editingId=null,localUrl=null,localFile=null,editingCode='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=s=>{s=Math.max(0,Number(s)||0);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}.${Math.floor((s%1)*10)}`};
const notice=(t,bad=false)=>{const e=$('notice');e.hidden=false;e.textContent=t;e.className='notice '+(bad?'bad':'good');clearTimeout(e._t);e._t=setTimeout(()=>e.hidden=true,6000)};
const emsg=(t,bad=false)=>{$('editorMsg').textContent=t;$('editorMsg').className='message '+(bad?'bad':'good')};
function showLogin(){ $('login').hidden=false;$('dashboard').hidden=true;$('logoutBtn').hidden=true;$('adminIdentity').hidden=true;$('detailModal').hidden=true }
function showDash(a){ $('login').hidden=true;$('dashboard').hidden=false;$('logoutBtn').hidden=false;$('adminIdentity').hidden=false;$('adminIdentity').textContent=a?.full_name||a?.email||'' }
async function guard(){const {data:{session}}=await sb.auth.getSession();if(!session){showLogin();return null}const {data:admin,error}=await sb.from('admin_users').select('id,full_name,email').eq('id',session.user.id).eq('active',true).maybeSingle();if(error||!admin){await sb.auth.signOut();showLogin();$('loginMsg').textContent='This account is not an active Raju Driving School admin.';return null}return {session,admin}}
async function login(){const email=$('email').value.trim(),password=$('password').value;if(!email||!password){$('loginMsg').textContent='Enter email and password.';return}$('loginBtn').disabled=true;$('loginMsg').textContent='Signing in…';const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('loginMsg').textContent=error.message;$('loginBtn').disabled=false;return}const a=await guard();$('loginBtn').disabled=false;if(a){showDash(a.admin);await refreshAll()}}
async function refreshAll(){const a=await guard();if(!a)return;await Promise.all([loadResults(),loadVideos()]);updateStats()}
async function loadResults(){const all=[];const pageSize=1000;for(let from=0;;from+=pageSize){const {data,error}=await sb.from('hpt_attempts').select('id,candidate_name,phone,started_at,completed_at,total_score,passed,clip_order').order('started_at',{ascending:false}).range(from,from+pageSize-1);if(error){notice(error.message,true);return}all.push(...(data||[]));if(!data||data.length<pageSize)break}results=all;renderResults()}
function isPassed(r){return r.passed===true||Number(r.total_score||0)>=60}
function renderResults(){const q=$('searchResults').value.trim().toLowerCase(),f=$('resultFilter').value;const rows=results.filter(r=>(!q||`${r.candidate_name} ${r.phone}`.toLowerCase().includes(q))&&(f==='all'||(f==='pass'&&isPassed(r))||(f==='fail'&&!isPassed(r))));$('resultsBody').innerHTML=rows.map(r=>`<tr><td>${new Date(r.started_at).toLocaleString('en-IN')}</td><td><b>${esc(r.candidate_name)}</b></td><td>${esc(r.phone)}</td><td class="score">${Number(r.total_score||0)} / 100</td><td class="${isPassed(r)?'pass':'fail'}">${isPassed(r)?'PASS':'NOT PASSED'}</td><td><button class="small" data-view="${r.id}">VIEW</button>${isPassed(r)?`<button class="small certificate-btn" title="Download HPT certificate" data-certificate="${r.id}">PRINT</button>`:''}<button class="small danger-outline" data-del-attempt="${r.id}">DELETE</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No examination results found.</td></tr>';document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showDetail(b.dataset.view));document.querySelectorAll('[data-certificate]').forEach(b=>b.onclick=()=>downloadCertificate(b.dataset.certificate));document.querySelectorAll('[data-del-attempt]').forEach(b=>b.onclick=()=>deleteAttempt(b.dataset.delAttempt))}
async function deleteAttempt(id){const r=results.find(x=>x.id===id);if(!r||!confirm(`Delete the complete examination record for ${r.candidate_name}? This cannot be undone.`))return;const {error}=await sb.from('hpt_responses').delete().eq('attempt_id',id);if(error){notice(error.message,true);return}const {error:e2}=await sb.from('hpt_attempts').delete().eq('id',id);if(e2){notice(e2.message,true);return}await loadResults();updateStats();notice('Examination record deleted.')}
async function showDetail(id){if(!(await guard()))return;const r=results.find(x=>x.id===id);if(!r)return;const {data:rs,error}=await sb.from('hpt_responses').select('response_no,click_time_seconds,hazard_no,awarded_marks,video_id').eq('attempt_id',id).order('response_no');if(error){notice(error.message,true);return}$('detailTitle').textContent=r.candidate_name;$('detailMeta').textContent=`${r.phone} • ${new Date(r.started_at).toLocaleString('en-IN')} • ${isPassed(r)?'PASS':'NOT PASSED'} • ${r.total_score}/100`;$('detailBody').innerHTML=`<div class="detail-clip"><span>Responses</span><b>${rs?.length||0}</b></div><div class="detail-clip"><span>Randomized order</span><b>${(r.clip_order||[]).map(esc).join(' → ')||'—'}</b></div>`+(rs||[]).map(x=>`<div class="detail-clip"><span>Response ${x.response_no} • ${Number(x.click_time_seconds).toFixed(1)}s • Hazard ${x.hazard_no||'—'}</span><b>+${x.awarded_marks}</b></div>`).join('');$('detailModal').hidden=false}
function updateStats(){const passed=results.filter(isPassed).length,avg=results.length?Math.round(results.reduce((a,r)=>a+Number(r.total_score||0),0)/results.length):0,ready=videos.filter(v=>v.active&&v.hazard_count>=2).length;$('statAttempts').textContent=results.length;$('statPassed').textContent=passed;$('statAverage').textContent=avg;$('statVideos').textContent=ready}
async function loadVideos(){const {data,error}=await sb.from('hpt_videos').select('id,clip_code,title,video_path,duration_seconds,active,updated_at,hpt_hazards(id,hazard_no,timestamp_seconds,label)').order('clip_code');if(error){notice(error.message,true);return}videos=(data||[]).map(v=>({...v,hazard_count:(v.hpt_hazards||[]).length}));renderVideos()}
function renderVideos(){$('videoGrid').innerHTML=videos.map(v=>`<article class="video-card"><div class="vc-top"><span class="clip">CLIP ${esc(v.clip_code)}</span><span class="status ${v.active?'on':'off'}">● ${v.active?'ACTIVE':'INACTIVE'}</span></div><h3>${esc(v.title)}</h3><p>${esc(v.video_path)}</p><div class="tags"><span>${Number(v.duration_seconds||0).toFixed(1)}s</span><span>${v.hazard_count}/2 hazards</span></div><div class="vc-actions"><button class="small" data-edit="${v.id}">EDIT & MARK</button><button class="small" data-toggle="${v.id}">${v.active?'DISABLE':'ENABLE'}</button></div></article>`).join('')||'<div class="empty">No HPT clips registered.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editVideo(b.dataset.edit));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggleVideo(b.dataset.toggle))}
function clearLocal(){if(localUrl){URL.revokeObjectURL(localUrl);localUrl=null}localFile=null}
function resetEditor(){clearLocal();editingId=null;editingCode='';$('videoFile').value='';$('fileName').textContent='No file selected';$('videoTitle').value='';$('h1t').value='';$('h2t').value='';$('h1label').value='';$('h2label').value='';$('active').checked=true;$('clipCodeDisplay').textContent='—';$('videoPathDisplay').textContent='videos/—';$('h1preview').textContent='Not set';$('h2preview').textContent='Not set';$('preview').removeAttribute('src');$('preview').load();$('previewEmpty').hidden=false;$('deleteVideo').hidden=true;emsg('')}
function nextClipCode(){const nums=videos.map(v=>parseInt(String(v.clip_code).replace(/\D/g,''),10)).filter(Number.isFinite);let n=Math.max(10,...nums)+1;while(videos.some(v=>String(v.clip_code).padStart(2,'0')===String(n).padStart(2,'0')))n++;return String(n).padStart(2,'0')}
function newVideo(){resetEditor();editingId=null;editingCode=nextClipCode();$('editor').hidden=false;$('editorEyebrow').textContent='NEW VIDEO';$('editorTitle').textContent='Upload HPT Video';$('editorSub').textContent='Select a video. Clip number and GitHub path are assigned automatically.';$('clipCodeDisplay').textContent=editingCode;$('videoPathDisplay').textContent=`videos/${editingCode}.webm`;$('videosPanel').hidden=false;$('editor').scrollIntoView({behavior:'smooth',block:'start'})}
function editVideo(id){const v=videos.find(x=>x.id===id);if(!v)return;clearLocal();editingId=id;editingCode=v.clip_code;$('editor').hidden=false;$('editorEyebrow').textContent='EDIT CLIP';$('editorTitle').textContent=`Edit Clip ${v.clip_code}`;$('editorSub').textContent='Replace the video if needed, adjust the two hazard points, then save once.';$('clipCodeDisplay').textContent=v.clip_code;$('videoPathDisplay').textContent=v.video_path;$('videoTitle').value=v.title;$('active').checked=!!v.active;$('videoFile').value='';$('fileName').textContent='No replacement selected';const hs=(v.hpt_hazards||[]).sort((a,b)=>a.hazard_no-b.hazard_no);$('h1t').value=hs.find(x=>x.hazard_no===1)?.timestamp_seconds??'';$('h2t').value=hs.find(x=>x.hazard_no===2)?.timestamp_seconds??'';$('h1label').value=hs.find(x=>x.hazard_no===1)?.label??'';$('h2label').value=hs.find(x=>x.hazard_no===2)?.label??'';updateHazardPreviews();$('preview').src=resolveVideoPath(v.video_path);$('previewEmpty').hidden=true;$('preview').load();$('deleteVideo').hidden=false;$('videosPanel').hidden=false;$('editor').scrollIntoView({behavior:'smooth',block:'start'})}
function resolveVideoPath(path){if(!path)return '';if(/^https?:\/\//i.test(path))return path;const clean=path.replace(/^\.\//,'');return new URL(clean,location.href).href}
function setMarkers(){const d=Number($('preview').duration)||50;const fill=Math.min(100,(Number($('preview').currentTime)||0)/Math.max(1,d)*100);$('trackFill').style.width=fill+'%';for(const n of [1,2]){const val=Number($(`h${n}t`).value),m=$(`marker${n}`);if(Number.isFinite(val)&&val>=0&&val<=d){m.hidden=false;m.style.left=(val/d*100)+'%'}else m.hidden=true}}
function updateHazardPreviews(){for(const n of [1,2]){$(`h${n}preview`).textContent=Number.isFinite(Number($(`h${n}t`).value))&&$(`h${n}t`).value!==''?fmt(Number($(`h${n}t`).value)):'Not set'}setMarkers()}
function setHaz(n){if(!$('preview').src||!Number.isFinite($('preview').currentTime)){emsg('Choose a playable video first.',true);return}const t=Number($('preview').currentTime.toFixed(1));$(`h${n}t`).value=t;updateHazardPreviews();emsg(`Hazard ${n} set at ${fmt(t)}.`)}
function validate(){const title=$('videoTitle').value.trim(),t1=Number($('h1t').value),t2=Number($('h2t').value),d=Number($('preview').duration);if(!localFile&&!editingId)return 'Choose a video file first.';if(!title)return 'Enter a clip title.';if(!Number.isFinite(t1)||!Number.isFinite(t2))return 'Set both developing hazards using the buttons below the video.';if(t1===t2)return 'Hazard timestamps must be different.';if(Number.isFinite(d)&&(t1>d||t2>d))return 'A hazard timestamp cannot be beyond the video duration.';return ''}
async function publishFile(path){const a=await guard();if(!a)return false;const fd=new FormData();fd.append('file',localFile);fd.append('path',path);fd.append('commit_message',`HPT: publish ${editingCode}`);const {data:{session}}=await sb.auth.getSession();let r;try{r=await fetch(C.githubPublishEndpoint,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`},body:fd})}catch(e){throw new Error(`Upload connection failed. The HPT GitHub Edge Function is not reachable. (${e.message})`)}const text=await r.text();let j={};try{j=JSON.parse(text)}catch{}if(!r.ok)throw new Error(j.error||`GitHub upload failed (${r.status}).`);return j}
async function saveVideo(){const problem=validate();if(problem){emsg(problem,true);return}const duration=Number($('preview').duration);let path=editingId?(videos.find(v=>v.id===editingId)?.video_path||`videos/${editingCode}.webm`):`videos/${editingCode}.webm`;if(localFile){const ext=(localFile.name.split('.').pop()||'webm').toLowerCase().replace(/[^a-z0-9]/g,'');path=`videos/${editingCode}.${ext||'webm'}`}
$('saveVideo').disabled=true;$('saveVideo').textContent='SAVING & PUBLISHING…';emsg('Uploading video…');try{if(localFile){await publishFile(path)}const payload={clip_code:editingCode,title:$('videoTitle').value.trim(),video_path:path,duration_seconds:Number((duration||50).toFixed(2)),active:$('active').checked,updated_at:new Date().toISOString()};let id=editingId;if(id){const {error}=await sb.from('hpt_videos').update(payload).eq('id',id);if(error)throw error}else{const {data:existing,error:qerr}=await sb.from('hpt_videos').select('id').eq('clip_code',editingCode).maybeSingle();if(qerr)throw qerr;if(existing?.id){id=existing.id;const {error}=await sb.from('hpt_videos').update(payload).eq('id',id);if(error)throw error}else{const {data,error}=await sb.from('hpt_videos').insert(payload).select('id').single();if(error)throw error;id=data.id}}
const {error:he}=await sb.from('hpt_hazards').upsert([{video_id:id,hazard_no:1,timestamp_seconds:Number($('h1t').value),label:$('h1label').value.trim()||'Developing hazard 1'},{video_id:id,hazard_no:2,timestamp_seconds:Number($('h2t').value),label:$('h2label').value.trim()||'Developing hazard 2'}],{onConflict:'video_id,hazard_no'});if(he)throw he;editingId=id;await loadVideos();updateStats();emsg('✓ Clip saved. Video published and both hazard timestamps are live.');notice(`Clip ${editingCode} saved successfully.`)}catch(e){emsg(e.message||'Could not save this clip.',true);notice(e.message||'Could not save this clip.',true)}finally{$('saveVideo').disabled=false;$('saveVideo').textContent='✓ SAVE & PUBLISH VIDEO'}}
async function toggleVideo(id){const v=videos.find(x=>x.id===id);if(!v)return;const {error}=await sb.from('hpt_videos').update({active:!v.active,updated_at:new Date().toISOString()}).eq('id',id);if(error){notice(error.message,true);return}await loadVideos();updateStats()}
async function deleteVideo(){
  const v=videos.find(x=>x.id===editingId);
  if(!v)return;
  const ok=confirm(`Delete Clip ${v.clip_code} permanently?\n\nThis will delete the video from GitHub and remove its HPT metadata and hazard timestamps from Supabase.\n\nThis cannot be undone.`);
  if(!ok)return;
  $('deleteVideo').disabled=true;$('deleteVideo').textContent='DELETING…';emsg('Deleting video from GitHub…');
  try{
    const a=await guard();if(!a)throw new Error('Admin session is required.');
    const {data:{session}}=await sb.auth.getSession();
    const fd=new FormData();fd.append('action','delete');fd.append('path',v.video_path);fd.append('commit_message',`HPT: delete ${v.clip_code}`);
    let r;try{r=await fetch(C.githubPublishEndpoint,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`},body:fd})}catch(e){throw new Error(`Delete connection failed. The HPT GitHub Edge Function is not reachable. (${e.message})`)}
    const text=await r.text();let j={};try{j=JSON.parse(text)}catch{}
    if(!r.ok)throw new Error(j.error||`GitHub delete failed (${r.status}).`);
    emsg('GitHub video deleted. Removing HPT metadata…');
    const {error:h}=await sb.from('hpt_hazards').delete().eq('video_id',editingId);if(h)throw h;
    const {error}=await sb.from('hpt_videos').delete().eq('id',editingId);if(error)throw error;
    const wasMissing=!!j.missing;
    closeEditor();await loadVideos();updateStats();notice(wasMissing?`Clip ${v.clip_code} metadata deleted. GitHub file was already missing.`:`Clip ${v.clip_code} deleted from GitHub and Supabase.`);
  }catch(e){emsg(e.message||'Could not delete this clip.',true);notice(e.message||'Could not delete this clip.',true)}
  finally{$('deleteVideo').disabled=false;$('deleteVideo').textContent='Delete clip'}
}
function closeEditor(){clearLocal();$('editor').hidden=true;editingId=null;editingCode=''}
async function imageData(url){return await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=img.naturalWidth||img.width;c.height=img.naturalHeight||img.height;const x=c.getContext('2d');x.drawImage(img,0,0);resolve(c.toDataURL('image/png'))};img.onerror=reject;img.src=url+'?v='+Date.now()})}
async function downloadCertificate(id){const r=results.find(x=>x.id===id);if(!r||!isPassed(r))return;if(!window.jspdf?.jsPDF){notice('Certificate generator is not available. Please refresh the page.',true);return}const btn=document.querySelector(`[data-certificate=\"${CSS.escape(id)}\"]`);if(btn){btn.disabled=true;btn.textContent='…'}try{const {jsPDF}=window.jspdf;const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});const W=297,H=210;doc.setFillColor(7,16,25);doc.rect(0,0,W,H,'F');doc.setDrawColor(255,196,0);doc.setLineWidth(1.5);doc.rect(8,8,W-16,H-16);doc.setLineWidth(.35);doc.rect(13,13,W-26,H-26);let logo=null;try{logo=await imageData('raju-logo.png')}catch{}if(logo)doc.addImage(logo,'PNG',18,18,35,35);doc.setTextColor(255,196,0);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('RAJU MOTOR DRIVING SCHOOL',W/2,27,{align:'center'});doc.setTextColor(245,248,251);doc.setFontSize(29);doc.text('CERTIFICATE OF HAZARD PERCEPTION',W/2,52,{align:'center'});doc.setFontSize(14);doc.setTextColor(148,167,181);doc.text('This certificate is awarded to',W/2,70,{align:'center'});doc.setTextColor(255,255,255);doc.setFontSize(27);doc.text(String(r.candidate_name||'Candidate'),W/2,88,{align:'center'});doc.setDrawColor(255,196,0);doc.line(70,94,227,94);doc.setTextColor(148,167,181);doc.setFontSize(13);doc.text('for successfully completing the Raju Motor Driving School Hazard Perception Test',W/2,108,{align:'center'});doc.setTextColor(255,196,0);doc.setFontSize(22);doc.text(`SCORE: ${Number(r.total_score||0)} / 100`,W/2,128,{align:'center'});doc.setTextColor(63,228,123);doc.setFontSize(17);doc.text('PASS',W/2,141,{align:'center'});doc.setTextColor(148,167,181);doc.setFontSize(10);const d=new Date(r.completed_at||r.started_at);doc.text(`Date: ${d.toLocaleDateString('en-IN')}`,55,171);doc.text(`Certificate No: HPT-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}-${String(r.id).slice(0,8).toUpperCase()}`,W-55,171,{align:'right'});doc.setTextColor(245,248,251);doc.setFontSize(11);doc.text('RAJU MOTOR DRIVING SCHOOL • CHALAKUDY',W/2,184,{align:'center'});doc.save(`Raju-HPT-Certificate-${String(r.candidate_name||'Candidate').replace(/[^a-z0-9]+/gi,'-')}.pdf`);notice(`Certificate downloaded for ${r.candidate_name}.`)}catch(e){console.error(e);notice('Could not generate the certificate.',true)}finally{if(btn){btn.disabled=false;btn.textContent='PRINT'}}}
function exportCsv(){const lines=[['Date','Candidate','Phone','Score','Status'],...results.map(r=>[new Date(r.started_at).toLocaleString('en-IN'),r.candidate_name,r.phone,r.total_score,isPassed(r)?'PASS':'NOT PASSED'])];const csv=lines.map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='raju-hpt-results.csv';a.click()}
$('loginBtn').onclick=login;$('password').onkeydown=e=>{if(e.key==='Enter')login()};$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};$('refreshAll').onclick=refreshAll;$('searchResults').oninput=renderResults;$('resultFilter').onchange=renderResults;$('exportCsv').onclick=exportCsv;$('newVideo').onclick=newVideo;$('closeEditor').onclick=closeEditor;$('saveVideo').onclick=saveVideo;$('deleteVideo').onclick=deleteVideo;$('mark1').onclick=()=>setHaz(1);$('mark2').onclick=()=>setHaz(2);$('annotationTrack').onclick=e=>{const r=$('annotationTrack').getBoundingClientRect();$('preview').currentTime=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*(Number($('preview').duration)||50);setMarkers()};for(const n of [1,2])$(`marker${n}`).onclick=e=>{e.stopPropagation();$('preview').currentTime=Number($(`h${n}t`).value)||0};$('preview').ontimeupdate=()=>{$('now').textContent=fmt($('preview').currentTime);$('dur').textContent=fmt($('preview').duration);setMarkers()};$('preview').onloadedmetadata=()=>{$('previewEmpty').hidden=true;$('dur').textContent=fmt($('preview').duration);setMarkers()};$('preview').onerror=()=>{$('previewEmpty').hidden=false;$('previewEmpty').textContent='Video could not be loaded. If this is an existing clip, verify its published path.'};$('videoFile').onchange=()=>{clearLocal();localFile=$('videoFile').files[0]||null;if(localFile){$('fileName').textContent=localFile.name;localUrl=URL.createObjectURL(localFile);$('preview').src=localUrl;$('previewEmpty').hidden=true;$('videoTitle').value=$('videoTitle').value||localFile.name.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ');$('preview').load()}};$('closeModal').onclick=()=>$('detailModal').hidden=true;$('detailModal').onclick=e=>{if(e.target===$('detailModal'))$('detailModal').hidden=true};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');const isR=t.dataset.tab==='results';$('resultsPanel').hidden=!isR;$('videosPanel').hidden=isR;$('editor').hidden=true});
let resultsPoll=null;
function startResultsPolling(){clearInterval(resultsPoll);resultsPoll=setInterval(async()=>{if(document.hidden||$('dashboard').hidden)return;try{await loadResults();updateStats()}catch(e){console.error('HPT results refresh failed',e)}},5000)}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!$('dashboard').hidden)loadResults()});
(async()=>{const a=await guard();if(a){showDash(a.admin);await refreshAll();startResultsPolling()}})();
})();
