(()=>{
'use strict';
const C=window.RAJU_HPT_CONFIG;
const sb=window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey);
const $=id=>document.getElementById(id);
let results=[], videos=[], editingId=null, localUrl=null, localFile=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=s=>{s=Math.max(0,Number(s)||0);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}.${String(Math.floor((s%1)*10))}`};
const notice=(text,bad=false)=>{const e=$('notice');e.hidden=false;e.textContent=text;e.className='notice '+(bad?'bad':'good');setTimeout(()=>e.hidden=true,4200)};
const editorMsg=(text,bad=false)=>{$('editorMsg').textContent=text;$('editorMsg').style.color=bad?'#ff8795':'#83f3a8'};
async function guard(){const {data:{session}}=await sb.auth.getSession();if(!session){showLogin();return null}const {data:admin,error}=await sb.from('admin_users').select('id,full_name,email').eq('id',session.user.id).eq('active',true).maybeSingle();if(error||!admin){await sb.auth.signOut();showLogin();$('loginMsg').textContent='This account is not registered as an active Raju Driving School admin.';return null}return {session,admin}}
function showLogin(){$('login').hidden=false;$('dashboard').hidden=true}function showDash(){$('login').hidden=true;$('dashboard').hidden=false}
async function login(){const email=$('email').value.trim(),password=$('password').value;if(!email||!password){$('loginMsg').textContent='Enter email and password.';return}$('loginBtn').disabled=true;$('loginMsg').textContent='Signing in…';const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('loginMsg').textContent=error.message;$('loginBtn').disabled=false;return}const ok=await guard();$('loginBtn').disabled=false;if(ok){showDash();await refreshAll()}}
async function refreshAll(){await Promise.all([loadResults(),loadVideos()]);updateStats()}
async function loadResults(){const {data,error}=await sb.from('hpt_attempts').select('id,candidate_name,phone,started_at,completed_at,total_score,passed,clip_order').order('started_at',{ascending:false}).limit(500);if(error){notice(error.message,true);return}results=data||[];renderResults()}
function renderResults(){const q=$('searchResults').value.trim().toLowerCase(),f=$('resultFilter').value;const rows=results.filter(r=>(!q||`${r.candidate_name} ${r.phone}`.toLowerCase().includes(q))&&(f==='all'||(f==='pass'&&r.passed)||(f==='fail'&&!r.passed)));$('resultsBody').innerHTML=rows.map(r=>`<tr><td>${new Date(r.started_at).toLocaleString('en-IN')}</td><td><b>${esc(r.candidate_name)}</b></td><td>${esc(r.phone)}</td><td class="score">${Number(r.total_score||0)} / 100</td><td class="${r.passed?'pass':'fail'}">${r.passed?'PASS':'NOT PASSED'}</td><td><button class="small-btn" data-detail="${r.id}">VIEW</button></td></tr>`).join('')||'<tr><td colspan="6" style="color:#7f929f;padding:25px">No examination results found.</td></tr>';document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showDetail(b.dataset.detail))}
async function showDetail(id){const r=results.find(x=>x.id===id);if(!r)return;const {data:rs}=await sb.from('hpt_responses').select('response_no,click_time_seconds,hazard_no,awarded_marks,video_id').eq('attempt_id',id).order('response_no');$('detailTitle').textContent=r.candidate_name;$('detailMeta').textContent=`${r.phone} • ${new Date(r.started_at).toLocaleString('en-IN')} • ${r.passed?'PASS':'NOT PASSED'} • ${r.total_score}/100`;const by={};(rs||[]).forEach(x=>(by[x.video_id||'unknown']??=[]).push(x));$('detailBody').innerHTML=`<div class="detail-clip"><span>Responses recorded</span><b>${rs?.length||0}</b></div><div class="detail-clip"><span>Clip order</span><b>${(r.clip_order||[]).map(x=>esc(x)).join(' → ')||'—'}</b></div>`+(rs||[]).map(x=>`<div class="detail-clip"><span>Response ${x.response_no} • ${Number(x.click_time_seconds).toFixed(1)}s • Hazard ${x.hazard_no||'—'}</span><b>+${x.awarded_marks}</b></div>`).join('');$('detailModal').hidden=false}
function updateStats(){const passed=results.filter(r=>r.passed).length;const avg=results.length?Math.round(results.reduce((a,r)=>a+Number(r.total_score||0),0)/results.length):0;const ready=videos.filter(v=>v.active&&Number(v.hazard_count||0)>=2);$('statAttempts').textContent=results.length;$('statPassed').textContent=passed;$('statAverage').textContent=avg;$('statVideos').textContent=ready.length;$('readyVideos').textContent=ready.length;$('readyHazards').textContent=ready.filter(v=>Number(v.hazard_count||0)>=2).length}
async function loadVideos(){const {data,error}=await sb.from('hpt_videos').select('id,clip_code,title,video_path,duration_seconds,active,updated_at,hpt_hazards(id,hazard_no,timestamp_seconds,label)').order('clip_code');if(error){notice(error.message,true);return}videos=(data||[]).map(v=>({...v,hazard_count:(v.hpt_hazards||[]).length}));renderVideos()}
function renderVideos(){ $('videoGrid').innerHTML=videos.map(v=>`<article class="video-card"><div class="vc-top"><span class="clip-badge">CLIP ${esc(v.clip_code)}</span><span class="status-dot ${v.active?'':'off'}">● ${v.active?'ACTIVE':'INACTIVE'}</span></div><h3>${esc(v.title)}</h3><p>${esc(v.video_path)}</p><div class="vc-meta"><span class="tag">${Number(v.duration_seconds||0).toFixed(1)}s</span><span class="tag">${v.hazard_count}/2 hazards</span></div><div class="vc-actions"><button class="small-btn" data-edit="${v.id}">EDIT & MARK</button><button class="small-btn" data-toggle="${v.id}">${v.active?'DISABLE':'ENABLE'}</button></div></article>`).join('')||'<div class="muted">No HPT videos registered yet.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editVideo(b.dataset.edit));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggleVideo(b.dataset.toggle))}
async function editVideo(id){const v=videos.find(x=>x.id===id);if(!v)return;editingId=id;localFile=null;if(localUrl){URL.revokeObjectURL(localUrl);localUrl=null}$('editor').hidden=false;$('editorEyebrow').textContent='EDIT VIDEO';$('editorTitle').textContent=`Edit Clip ${v.clip_code}`;$('clipCode').value=v.clip_code;$('videoTitle').value=v.title;$('videoPath').value=v.video_path;$('active').checked=!!v.active;$('deleteVideo').hidden=false;$('videoFile').value='';const hs=(v.hpt_hazards||[]).sort((a,b)=>a.hazard_no-b.hazard_no);$('h1t').value=hs.find(x=>x.hazard_no===1)?.timestamp_seconds??'';$('h2t').value=hs.find(x=>x.hazard_no===2)?.timestamp_seconds??'';$('h1label').value=hs.find(x=>x.hazard_no===1)?.label??'';$('h2label').value=hs.find(x=>x.hazard_no===2)?.label??'';$('preview').src=v.video_path;$('previewEmpty').hidden=true;setMarkers();$('editor').scrollIntoView({behavior:'smooth',block:'start'})}
function newVideo(){editingId=null;localFile=null;if(localUrl){URL.revokeObjectURL(localUrl);localUrl=null}$('editor').hidden=false;$('editorEyebrow').textContent='NEW VIDEO';$('editorTitle').textContent='Add HPT Video';['clipCode','videoTitle','videoPath','h1t','h2t','h1label','h2label'].forEach(id=>$(id).value='');$('active').checked=true;$('deleteVideo').hidden=true;$('videoFile').value='';$('preview').removeAttribute('src');$('preview').load();$('previewEmpty').hidden=false;setMarkers();$('editor').scrollIntoView({behavior:'smooth',block:'start'})}
function currentTime(){return Number($('preview').currentTime||0)}
function setHaz(n){const t=currentTime().toFixed(1);$(`h${n}t`).value=t;setMarkers();editorMsg(`Hazard ${n} locked at ${t}s. The video marker now reflects the timestamp.`)}
function setMarkers(){const d=Number($('preview').duration)||Number($('dur').dataset.raw)||50;const fill=Math.min(100,currentTime()/Math.max(1,d)*100);$('track-fill')?.style.setProperty('width',fill+'%');for(const n of [1,2]){const val=Number($(`h${n}t`).value);const m=$(`marker${n}`);if(Number.isFinite(val)&&val>=0&&val<=d){m.style.display='block';m.style.left=(val/d*100)+'%'}else m.style.display='none'}}
function seekFromTrack(e){const r=$('annotationTrack').getBoundingClientRect();const p=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));const d=Number($('preview').duration)||50;$('preview').currentTime=p*d;setMarkers()}
async function saveVideo(){const code=$('clipCode').value.trim(),title=$('videoTitle').value.trim(),path=$('videoPath').value.trim(),t1=Number($('h1t').value),t2=Number($('h2t').value),duration=Number($('preview').duration)||50;if(!code||!title||!path||!Number.isFinite(t1)||!Number.isFinite(t2)){editorMsg('Enter clip code, title, static path, and both hazard timestamps.',true);return}if(t1===t2){editorMsg('Hazard 1 and Hazard 2 must have different timestamps.',true);return}const payload={clip_code:code,title,video_path:path,duration_seconds:Number(duration.toFixed(2)),active:$('active').checked,updated_at:new Date().toISOString()};let id=editingId;if(id){const {error}=await sb.from('hpt_videos').update(payload).eq('id',id);if(error){editorMsg(error.message,true);return}}else{const {data,error}=await sb.from('hpt_videos').insert(payload).select('id').single();if(error){editorMsg(error.message,true);return}id=data.id}await sb.from('hpt_hazards').upsert([{video_id:id,hazard_no:1,timestamp_seconds:t1,label:$('h1label').value.trim()||'Developing hazard 1'},{video_id:id,hazard_no:2,timestamp_seconds:t2,label:$('h2label').value.trim()||'Developing hazard 2'}],{onConflict:'video_id,hazard_no'});editingId=id;await loadVideos();updateStats();editorMsg('Saved successfully. Both hazard timestamps are now stored in Supabase.');notice('HPT video metadata and hazard points saved.')}
async function toggleVideo(id){const v=videos.find(x=>x.id===id);if(!v)return;const {error}=await sb.from('hpt_videos').update({active:!v.active,updated_at:new Date().toISOString()}).eq('id',id);if(error){notice(error.message,true);return}await loadVideos();updateStats()}
async function deleteVideo(){if(!editingId||!confirm('Delete this HPT video metadata and its hazard annotations? The GitHub video file will not be deleted.'))return;const {error}=await sb.from('hpt_videos').delete().eq('id',editingId);if(error){editorMsg(error.message,true);return}closeEditor();await loadVideos();updateStats();notice('Video metadata deleted. Static/GitHub file remains untouched.')}
function closeEditor(){$('editor').hidden=true;editingId=null;if(localUrl){URL.revokeObjectURL(localUrl);localUrl=null}}
function downloadPack(){const code=$('clipCode').value.trim()||'clip';const data={clip_code:code,title:$('videoTitle').value.trim(),video_path:$('videoPath').value.trim(),duration_seconds:Number($('preview').duration||50),hazards:[{hazard_no:1,timestamp_seconds:Number($('h1t').value),label:$('h1label').value.trim()},{hazard_no:2,timestamp_seconds:Number($('h2t').value),label:$('h2label').value.trim()}]};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`hpt-${code}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCsv(){const lines=[['Date','Candidate','Phone','Score','Status'],...results.map(r=>[new Date(r.started_at).toLocaleString('en-IN'),r.candidate_name,r.phone,r.total_score,r.passed?'PASS':'NOT PASSED'])];const csv=lines.map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='raju-hpt-results.csv';a.click()}
$('loginBtn').onclick=login;$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};$('refreshAll').onclick=refreshAll;$('searchResults').oninput=renderResults;$('resultFilter').onchange=renderResults;$('exportCsv').onclick=exportCsv;$('openVideos').onclick=()=>$('librarySection').scrollIntoView({behavior:'smooth'});$('newVideo').onclick=newVideo;$('closeEditor').onclick=closeEditor;$('saveVideo').onclick=saveVideo;$('deleteVideo').onclick=deleteVideo;$('downloadPack').onclick=downloadPack;$('mark1').onclick=()=>setHaz(1);$('mark2').onclick=()=>setHaz(2);$('jump1').onclick=()=>{$('preview').currentTime=Number($('h1t').value)||0};$('jump2').onclick=()=>{$('preview').currentTime=Number($('h2t').value)||0};$('annotationTrack').onclick=seekFromTrack;for(const n of [1,2])$(`marker${n}`).onclick=e=>{e.stopPropagation();$('preview').currentTime=Number($(`h${n}t`).value)||0};$('preview').ontimeupdate=()=>{const t=currentTime();$('now').textContent=fmt(t);const d=Number($('preview').duration)||50;$('dur').textContent=fmt(d);$('dur').dataset.raw=d;setMarkers()};$('preview').onloadedmetadata=()=>{$('previewEmpty').hidden=true;$('dur').textContent=fmt($('preview').duration);$('dur').dataset.raw=$('preview').duration;setMarkers()};$('videoFile').onchange=()=>{localFile=$('videoFile').files[0];if(localUrl)URL.revokeObjectURL(localUrl);if(localFile){localUrl=URL.createObjectURL(localFile);$('preview').src=localUrl;$('previewEmpty').hidden=true;$('videoPath').value=$('videoPath').value||`videos/${localFile.name}`;$('videoTitle').value=$('videoTitle').value||localFile.name.replace(/\.[^.]+$/,'');$('preview').load()}};$('closeModal').onclick=()=>$('detailModal').hidden=true;$('detailModal').addEventListener('click',e=>{if(e.target===$('detailModal'))$('detailModal').hidden=true});
(async()=>{const auth=await guard();if(auth){showDash();await refreshAll()}})();
})();