const C=window.RAJU_HPT_CONFIG, sb=window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey), $=id=>document.getElementById(id);
let file=null,url=null,metadata=null;
$('back').onclick=()=>location.href='index.html';
$('loginBtn').onclick=async()=>{const {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('loginMsg').textContent=error.message;return}await init()};
async function init(){const {data:{user}}=await sb.auth.getUser();if(!user){$('login').hidden=false;$('dash').hidden=true;return}$('login').hidden=true;$('dash').hidden=false;await refreshResults();await refreshVideos()}
async function refreshResults(){const {data,error}=await sb.from('hpt_attempts').select('id,candidate_name,phone,started_at,total_score,passed').order('started_at',{ascending:false});if(error){$('resultsBody').innerHTML=`<tr><td colspan="5">${error.message}</td></tr>`;return}$('resultsBody').innerHTML=(data||[]).map(r=>`<tr><td>${new Date(r.started_at).toLocaleString()}</td><td>${esc(r.candidate_name)}</td><td>${esc(r.phone)}</td><td><b>${r.total_score}/100</b></td><td class="${r.passed?'pass':'fail'}">${r.passed?'PASS':'NOT PASSED'}</td></tr>`).join('')||'<tr><td colspan="5">No results yet.</td></tr>'}
async function refreshVideos(){const {data,error}=await sb.from('hpt_videos').select('id,clip_code,title,video_path,duration_seconds,active,updated_at').order('clip_code');if(error){$('library').textContent=error.message;return}$('videoCount').textContent=`${data?.length||0} registered`;$('library').innerHTML=(data||[]).map(v=>`<div class="row"><div><b>${esc(v.clip_code)} — ${esc(v.title)}</b><small>${esc(v.video_path)} • ${v.active?'ACTIVE':'INACTIVE'}</small></div><button data-edit="${v.id}">EDIT</button></div>`).join('')||'<p class="muted">No Supabase video metadata yet.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editVideo(b.dataset.edit))}
async function editVideo(id){const {data:v}=await sb.from('hpt_videos').select('*').eq('id',id).single();const {data:h}=await sb.from('hpt_hazards').select('*').eq('video_id',id).order('hazard_no');$('videoTitle').value=v.title;$('videoPath').value=v.video_path;$('h1t').value=h?.find(x=>x.hazard_no===1)?.timestamp_seconds??'';$('h2t').value=h?.find(x=>x.hazard_no===2)?.timestamp_seconds??'';$('h1label').value=h?.find(x=>x.hazard_no===1)?.label??'';$('h2label').value=h?.find(x=>x.hazard_no===2)?.label??'';metadata={id:v.id}}
$('videoFile').onchange=()=>{file=$('videoFile').files[0];if(url)URL.revokeObjectURL(url);if(file){url=URL.createObjectURL(file);$('preview').src=url}};
$('preview').ontimeupdate=()=>{const t=$('preview').currentTime;$('now').textContent=`${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`};
$('mark1').onclick=()=>{$('h1t').value=$('preview').currentTime.toFixed(1)};$('mark2').onclick=()=>{$('h2t').value=$('preview').currentTime.toFixed(1)};
$('saveVideo').onclick=async()=>{const title=$('videoTitle').value.trim(),path=$('videoPath').value.trim(),t1=Number($('h1t').value),t2=Number($('h2t').value);if(!title||!path||!Number.isFinite(t1)||!Number.isFinite(t2)){alert('Enter title, static video path and both hazard timestamps.');return}let id=metadata?.id;if(id){const {error}=await sb.from('hpt_videos').update({title,video_path:path,duration_seconds:Number($('preview').duration||50),updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);await sb.from('hpt_hazards').upsert([{video_id:id,hazard_no:1,timestamp_seconds:t1,label:$('h1label').value.trim()||'Developing hazard 1'},{video_id:id,hazard_no:2,timestamp_seconds:t2,label:$('h2label').value.trim()||'Developing hazard 2'}],{onConflict:'video_id,hazard_no'})}else{const code=path.match(/(\d+)\.\w+$/)?.[1]||String(Date.now()).slice(-4);const {data:v,error}=await sb.from('hpt_videos').insert({clip_code:code,title,video_path:path,duration_seconds:Number($('preview').duration||50),active:true}).select().single();if(error)return alert(error.message);id=v.id;await sb.from('hpt_hazards').insert([{video_id:id,hazard_no:1,timestamp_seconds:t1,label:$('h1label').value.trim()||'Developing hazard 1'},{video_id:id,hazard_no:2,timestamp_seconds:t2,label:$('h2label').value.trim()||'Developing hazard 2'}])}metadata={id};alert('HPT video metadata saved. Now publish the video file to the static path shown above.');await refreshVideos()};
$('downloadPack').onclick=async()=>{if(!file){alert('Choose the video file first.');return}const path=$('videoPath').value.trim()||`videos/${file.name}`;const data={title:$('videoTitle').value.trim()||file.name,video_path:path,hazards:[{t:Number($('h1t').value),label:$('h1label').value.trim()},{t:Number($('h2t').value),label:$('h2label').value.trim()}]};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name.replace(/\.[^.]+$/,'')+'.json';a.click();const b=document.createElement('a');b.href=url;b.download=file.name;b.click();alert('Downloaded the video + metadata package. Put the video in the GitHub videos/ folder and keep the JSON as your annotation record.');};
$('refresh').onclick=refreshResults;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tabpage').forEach(x=>x.hidden=x.id!==b.dataset.tab);if(b.dataset.tab==='videos')refreshVideos()});function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[c]) )}init();
