(()=>{
'use strict';
if(!document.getElementById('hptHiddenFix')){const s=document.createElement('style');s.id='hptHiddenFix';s.textContent='[hidden]{display:none!important}';document.head.appendChild(s);}
const $=id=>document.getElementById(id);
const C=window.RAJU_HPT_CONFIG;
let clips=[], order=[], pos=0, responses=[], scores=[], running=false, finishing=false, timer=null;
let candidate={name:'',phone:''}, sound=true;
const video=$('video');
const fmt=s=>{s=Math.max(0,Math.ceil(Number(s)||0));return `00:${String(s).padStart(2,'0')}`};
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const show=(id,on)=>{$(id).hidden=!on};
const toast=(t,bad=false)=>{const e=$('toast');e.textContent=t;e.className='toast show'+(bad?' bad':'');clearTimeout(e._t);e._t=setTimeout(()=>e.className='toast',1300)};
function update(){const d=Math.min(C.clipLimitSeconds,video.duration||C.clipLimitSeconds);$('clipNo').textContent=`${pos+1} / ${order.length}`;$('clipNo2').textContent=`${pos+1} / ${order.length}`;$('timer').textContent=fmt(Math.max(0,C.clipLimitSeconds-video.currentTime));$('elapsed').textContent=fmt(video.currentTime);$('duration').textContent=fmt(d);$('respCount').textContent=`${responses.length} / ${C.maxResponsesPerClip}`}
function timeline(){const t=$('track');t.innerHTML='';const d=Math.max(1,Math.min(C.clipLimitSeconds,video.duration||C.clipLimitSeconds));responses.forEach(r=>{const m=document.createElement('div');m.className='mark';m.style.left=Math.min(100,r.t/d*100)+'%';m.title=r.points?`+${r.points} marks`:'0 marks';m.textContent='⚑';t.appendChild(m)})}
function hit(x,y,points){const e=document.createElement('div');e.className='hit';e.style.left=x+'px';e.style.top=y+'px';e.innerHTML=`<b>${points?`+${points} MARKS`:'RESPONSE'}</b>`;$('clickLayer').appendChild(e);setTimeout(()=>e.remove(),900)}
function resetClip(){responses=[];finishing=false;timeline();update()}
function staticHazards(code){return (C.staticHazards?.[String(code).padStart(2,'0')]||[]).map((h,i)=>({...h,hazard_no:i+1}))}
async function supabase(){if(window._sb)return window._sb;try{if(!window.supabase?.createClient)return null;window._sb=window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey);return window._sb}catch{return null}}
async function loadClips(){clips=C.staticClips.map(x=>({...x,hazards:staticHazards(x.clip_code)}));const sb=await supabase();if(sb){const {data:vs}=await sb.from('hpt_videos').select('id,clip_code,title,video_path,duration_seconds,active').eq('active',true);if(vs?.length){const {data:hs}=await sb.from('hpt_hazards').select('video_id,hazard_no,timestamp_seconds,label');const by={};(hs||[]).forEach(h=>(by[h.video_id]??=[]).push({t:Number(h.timestamp_seconds),label:h.label||`Hazard ${h.hazard_no}`,hazard_no:h.hazard_no}));const remote=vs.map(v=>({...v,file:v.video_path.startsWith('http')?v.video_path:(v.video_path.startsWith('./')?v.video_path:C.videoBase+v.video_path.replace(/^videos\//,'')),hazards:(by[v.id]||[])})).filter(v=>v.hazards.length>=2); if(remote.length) clips=remote;}}
// If Supabase has no videos yet, static local clips remain usable.
return clips.filter(c=>c.active&&c.video_path&&c.hazards?.length>=2)}
async function saveAttempt(){const sb=await supabase();if(!sb)return null;const total=scores.reduce((a,b)=>a+b,0);const {data,error}=await sb.from('hpt_attempts').insert({candidate_name:candidate.name,phone:candidate.phone,started_at:new Date(Date.now()-C.examClipCount*C.clipLimitSeconds*1000).toISOString(),completed_at:new Date().toISOString(),total_score:total,passed:total>=C.passMark,clip_order:order.map(c=>c.clip_code)}).select('id').single();if(error)return null;return data.id}
async function saveResponses(id){const sb=await supabase();if(!sb||!id)return;const rows=[];for(let i=0;i<scores.length;i++){const clip=order[i];const rs=clip._responses||[];for(const r of rs)rows.push({attempt_id:id,video_id:clip.id||null,response_no:r.response_no,click_time_seconds:r.t,hazard_no:r.hazard_no||null,awarded_marks:r.points})}if(rows.length)await sb.from('hpt_responses').insert(rows)}
function loadClip(){resetClip();running=false;clearTimeout(timer);video.pause();video.removeAttribute('src');video.src=order[pos].file;video.muted=!sound;video.load();$('playOverlay').hidden=true;video.onloadedmetadata=()=>{video.currentTime=0;update();timeline();const p=video.play();if(p?.catch)p.catch(()=>{$('playOverlay').hidden=false});running=true;clearTimeout(timer);timer=setTimeout(finishClip,C.clipLimitSeconds*1000)};video.onerror=()=>{running=false;$('playOverlay').hidden=false;$('playNow').textContent='PLAY CLIP';toast('Video could not be loaded',true)}}
async function finishClip(){if(finishing)return;finishing=true;running=false;clearTimeout(timer);video.pause();scores.push(Math.max(0,Math.min(10,scoreThis())));pos++;if(pos>=order.length){await finishExam();return}setTimeout(()=>{finishing=false;loadClip()},220)}
function scoreThis(){return responses.reduce((a,r)=>a+r.points,0)}
async function finishExam(){const total=scores.reduce((a,b)=>a+b,0);const id=await saveAttempt();await saveResponses(id);show('examScreen',false);show('resultScreen',true);$('candidateResult').textContent=`${candidate.name} • ${candidate.phone}`;$('finalScore').textContent=`${total} / 100`;$('passText').textContent=total>=C.passMark?'PASS — EXAMINATION STANDARD MET':'NOT PASSED — BELOW PASS MARK';$('passText').className='status '+(total>=C.passMark?'pass':'fail');$('resultDetails').innerHTML='<table><thead><tr><th>CLIP</th><th>SCORE</th></tr></thead><tbody>'+scores.map((s,i)=>`<tr><td>Clip ${String(i+1).padStart(2,'0')}</td><td>${s} / 10</td></tr>`).join('')+'</tbody></table>';const passed=total>=C.passMark;show('certificateBtn',passed);show('certificateNote',passed);$('certificateBtn').onclick=()=>downloadCertificate(total)}
function downloadCertificate(total){try{const jsp=window.jspdf?.jsPDF;if(!jsp){toast('Certificate PDF library is unavailable',true);return}const doc=new jsp({orientation:'landscape',unit:'mm',format:'a4'});const W=297,H=210;doc.setFillColor(7,16,24);doc.rect(0,0,W,H,'F');doc.setDrawColor(255,196,0);doc.setLineWidth(1.2);doc.rect(8,8,W-16,H-16);doc.setDrawColor(239,35,60);doc.setLineWidth(.5);doc.rect(12,12,W-24,H-24);const img=$('resultScreen').querySelector('.resultLogo');if(img&&img.complete){const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);const data=c.toDataURL('image/png');doc.addImage(data,'PNG',18,18,35,26)}doc.setTextColor(255,196,0);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('RAJU DRIVING SCHOOL • CHALAKUDY • SINCE 1969',W/2,29,{align:'center'});doc.setTextColor(255,255,255);doc.setFontSize(30);doc.text('CERTIFICATE OF ACHIEVEMENT',W/2,60,{align:'center'});doc.setTextColor(255,196,0);doc.setFontSize(17);doc.text('HAZARD PERCEPTION TEST',W/2,73,{align:'center'});doc.setTextColor(190,204,214);doc.setFont('helvetica','normal');doc.setFontSize(11);doc.text('This certificate is presented to',W/2,91,{align:'center'});doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(25);doc.text(candidate.name,W/2,106,{align:'center'});doc.setTextColor(190,204,214);doc.setFont('helvetica','normal');doc.setFontSize(11);doc.text('for successfully passing the Raju Driving School Hazard Perception Test.',W/2,119,{align:'center'});doc.setTextColor(255,196,0);doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text(`SCORE: ${total} / 100`,W/2,138,{align:'center'});doc.setTextColor(57,255,114);doc.setFontSize(13);doc.text('PASS',W/2,149,{align:'center'});doc.setTextColor(170,183,194);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(`Candidate Mobile: ${candidate.phone}`,24,178);doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`,W-24,178,{align:'right'});doc.setDrawColor(120,135,145);doc.line(24,169,90,169);doc.line(W-90,169,W-24,169);doc.setFontSize(8);doc.text('Authorized — Raju Driving School',57,174,{align:'center'});doc.text('Computer-Based HPT Result',W-57,174,{align:'center'});doc.save(`Raju-HPT-Certificate-${candidate.name.replace(/[^a-z0-9]+/gi,'-')}.pdf`)}catch(e){console.error(e);toast('Could not create certificate PDF',true)}}
async function begin(){const n=$('name').value.trim(),p=$('phone').value.trim();if(!n||!p){toast('Enter candidate name and phone number',true);return}clips=await loadClips();if(clips.length<C.examClipCount){toast(`Need ${C.examClipCount} active clips with 2 hazards each`,true);return}candidate={name:n,phone:p};$('candName').textContent=n;$('candPhone').textContent=p;order=shuffle(clips).slice(0,C.examClipCount);pos=0;scores=[];show('startScreen',false);show('resultScreen',false);show('examScreen',true);loadClip()}
$('startBtn').onclick=begin;$('resultClose').onclick=()=>{show('resultScreen',false);show('startScreen',true)};$('newBtn').onclick=()=>{show('resultScreen',false);show('startScreen',true)};$('skipBtn').onclick=finishClip;$('soundBtn').onclick=()=>{sound=!sound;video.muted=!sound;$('soundBtn').textContent=sound?'🔊':'🔇'};$('fullBtn').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()};$('helpBtn').onclick=()=>toast('Tap when a developing hazard becomes apparent. Maximum 5 responses per clip.');$('exitBtn').onclick=()=>{if(confirm('Exit the examination? This attempt will be incomplete.')){clearTimeout(timer);video.pause();running=false;show('examScreen',false);show('startScreen',true)}};$('playNow').onclick=()=>video.play().then(()=>{$('playOverlay').hidden=true;running=true;clearTimeout(timer);timer=setTimeout(finishClip,C.clipLimitSeconds*1000)}).catch(()=>toast('Video could not start',true));
video.addEventListener('timeupdate',()=>{update();timeline()});video.addEventListener('ended',finishClip);video.addEventListener('click',async e=>{if(!running||finishing)return;if(responses.length>=C.maxResponses){toast('MAX 5 RESPONSES',true);return}const rect=video.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,t=video.currentTime,hz=order[pos].hazards||[];let best=null;hz.forEach((h,i)=>{const hn=h.hazard_no||i+1;if(responses.some(r=>r.hazard_no===hn))return;const delta=t-Number(h.t);if(delta>=0&&delta<=5){const pts=delta<=1.5?5:delta<=2.5?4:delta<=3.5?3:2;if(!best||pts>best.points)best={hazard_no:hn,points:pts}}});const r={t,response_no:responses.length+1,hazard_no:best?.hazard_no||null,points:best?.points||0};responses.push(r);hit(x,y,r.points);toast(r.points?`+${r.points} MARKS`:'RESPONSE RECORDED');timeline();update();order[pos]._responses=responses});
$('startScreen').querySelector('input')?.focus();
show('startScreen',true);show('examScreen',false);show('resultScreen',false);
})();
