(function(){
const clips=[
 {n:1,src:'assets/videos/clip-01.mp4',haz:[{t:3.0,label:'Pedestrian on left — possible crossing'},{t:4.3,label:'Motorcycle crossing ahead'}]},
 {n:2,src:'assets/videos/clip-02.mp4',haz:[{t:3.0,label:'Person crossing from centre median'},{t:3.5,label:'Bike entering from left'}]},
 {n:3,src:'assets/videos/clip-03.mp4',haz:[{t:2.07,label:'Vehicle reversing into main road'},{t:10.40,label:'Cycle entering main road'}]},
 {n:4,src:'assets/videos/clip-04.mp4',haz:[{t:4.30,label:'Pedestrian starting to cross'},{t:23.40,label:'Auto rickshaw entering road'}]},
 {n:5,src:null,haz:[]},{n:6,src:null,haz:[]},{n:7,src:null,haz:[]},{n:8,src:null,haz:[]},{n:9,src:null,haz:[]},{n:10,src:null,haz:[]}
];
const S={mode:'',i:0,clicks:[],scores:[],started:0,candidate:null,timer:null};
const $=s=>document.querySelector(s); const fmt=t=>Math.max(0,t).toFixed(1)+'s';
function start(mode){S.mode=mode; S.i=0; S.clicks=[]; S.scores=[]; S.started=0; S.candidate=null; renderIntro();}
function renderIntro(){const root=$(S.mode==='actual'?'#actualApp':'#practiceApp'); root.innerHTML=S.mode==='actual'?`<section class="panel intro"><div class="eyebrow">RAJU MOTOR DRIVING SCHOOL</div><h1>Hazard Perception Test</h1><p>This is an examination-style hazard perception session. Enter the candidate details for reference. The details remain visible during the examination.</p><div class="fields"><div class="field"><label>Candidate Name</label><input id="name" autocomplete="off"></div><div class="field"><label>Phone Number</label><input id="phone" inputmode="tel" autocomplete="off"></div></div><div class="summary"><div class="summaryRow"><span>Examination format</span><b>10 video clips • 100 marks</b></div><div class="summaryRow"><span>Pass mark</span><b>60 / 100</b></div><div class="summaryRow"><span>Responses per clip</span><b>Maximum 5</b></div></div><p class="security">Candidate details are for reference in this local training system.</p><button id="begin" class="btn primary">BEGIN EXAMINATION</button></section>`:`<section class="panel intro"><div class="eyebrow">TRAINING MODE</div><h1>Hazard Perception Practice</h1><p>Click the video when you identify a developing hazard. Your responses are shown on the timeline and can be reviewed.</p><div class="summary"><div class="summaryRow"><span>Clips available</span><b>4</b></div><div class="summaryRow"><span>Maximum responses</span><b>5 per clip</b></div></div><button id="begin" class="btn primary">START PRACTICE</button></section>`; $('#begin').onclick=()=>{if(S.mode==='actual'){const n=$('#name').value.trim(),p=$('#phone').value.trim();if(!n||!p){alert('Please enter candidate name and phone number.');return}S.candidate={name:n,phone:p}}; S.started=Date.now();renderExam();};}
function renderExam(){const root=$(S.mode==='actual'?'#actualApp':'#practiceApp'); const c=clips[S.i]; if(!c.src){finish();return} const total=clips.length; const dots=clips.map((x,k)=>`<span class="dot ${k<S.i?'done':''} ${k===S.i?'current':''}"></span>`).join(''); const who=S.candidate?`<div class="who"><div><small>Candidate</small><strong>${esc(S.candidate.name)}</strong></div><div><small>Phone</small><strong>${esc(S.candidate.phone)}</strong></div><div><small>Test</small><strong>HPT Examination</strong></div></div>`:`<div class="who"><div><small>Mode</small><strong>Practice Test</strong></div></div>`; root.innerHTML=`<section class="panel candidate">${who}<div class="status">${S.mode==='actual'?'EXAMINATION IN PROGRESS':'PRACTICE IN PROGRESS'}</div></section><section class="panel examHead"><div><b>CLIP ${String(c.n).padStart(2,'0')}</b><div class="security">${S.i+1} OF ${total} CLIPS</div></div><div class="progress">${dots}</div><div id="timer" class="timer">01:00</div></section><section class="panel content"><div class="instruction">Watch the road scene carefully. Click when you recognise a developing hazard. <b>Do not click repeatedly.</b></div><div class="videoFrame"><video id="video" src="${c.src}" playsinline preload="auto"></video><div id="overlay" class="videoOverlay"></div></div><div class="timeline"><div class="axis"></div><div id="flags"></div></div><div class="responseBar"><span id="count" class="responseCount">RESPONSES: 0 / 5</span><span class="security">CLIP RESPONSES ARE LOCKED AFTER THE CLIP ENDS</span></div><div class="nav"><div class="practiceTools">${S.mode==='practice'?'<button id="replay" class="btn muted">REPLAY</button><button id="prev" class="btn muted">PREVIOUS</button>':''}</div><button id="next" class="btn primary">${S.i===3?'FINISH':'NEXT CLIP'} →</button></div></section>`; wire(c);}
function wire(c){const v=$('#video'),o=$('#overlay'),f=$('#flags'),count=$('#count'); let ended=false,answered=[]; v.controls=false; v.currentTime=0; v.play().catch(()=>{}); let startTime=Date.now(); S.clicks=[]; $('#timer').textContent='01:00'; clearInterval(S.timer); S.timer=setInterval(()=>{const remain=Math.max(0,60-(Date.now()-startTime)/1000); $('#timer').textContent='00:'+String(Math.ceil(remain)).padStart(2,'0');if(remain<=0){clearInterval(S.timer);ended=true;v.pause();o.classList.add('block');}},100); v.addEventListener('ended',()=>{ended=true;o.classList.add('block');}); o.addEventListener('click',e=>{if(ended||S.clicks.length>=5)return; const t=v.currentTime; S.clicks.push(t); const x=(t/Math.max(v.duration||1,.1))*100; const flag=document.createElement('div');flag.className='flag';flag.style.left=Math.min(98,Math.max(2,x))+'%';flag.textContent=S.clicks.length;f.appendChild(flag);const tl=document.createElement('div');tl.className='timeLabel';tl.style.left=Math.min(98,Math.max(2,x))+'%';tl.textContent=fmt(t);f.appendChild(tl);count.textContent=`RESPONSES: ${S.clicks.length} / 5`;});
 $('#next').onclick=()=>{grade(c); if(S.mode==='actual'){if(S.i<3){S.i++;renderExam()}else finish()}else{if(S.i<3){S.i++;renderExam()}else finish()}};
 if($('#replay'))$('#replay').onclick=()=>{v.currentTime=0;ended=false;o.classList.remove('block');S.clicks=[];f.innerHTML='';count.textContent='RESPONSES: 0 / 5';startTime=Date.now();v.play().catch(()=>{})};
 if($('#prev'))$('#prev').onclick=()=>{if(S.i>0){S.i--;renderExam()}};
}
function grade(c){if(S.clicks.length>5){S.scores.push(0);return} let used=new Set(),score=0;S.clicks.forEach(t=>c.haz.forEach((h,idx)=>{if(used.has(idx))return;const d=t-h.t;if(d>=0&&d<=1.5){score+=5;used.add(idx)}else if(d>1.5&&d<=2.5){score+=4;used.add(idx)}else if(d>2.5&&d<=3.5){score+=3;used.add(idx)}else if(d>3.5&&d<=5){score+=2;used.add(idx)}}));S.scores.push(Math.min(10,score));}
function finish(){clearInterval(S.timer);const total=S.scores.reduce((a,b)=>a+b,0);const max=S.scores.length*10;const pass=max?total>=60:'—';const root=$(S.mode==='actual'?'#actualApp':'#practiceApp');root.innerHTML=`<section class="panel result"><div class="eyebrow">RAJU MOTOR DRIVING SCHOOL</div><h1>${S.mode==='actual'?'EXAMINATION COMPLETE':'PRACTICE COMPLETE'}</h1>${S.candidate?`<p><b>${esc(S.candidate.name)}</b> • ${esc(S.candidate.phone)}</p>`:''}<div class="score">${total}<small> / ${max}</small></div><div class="pass">${S.mode==='actual'?(total>=60?'PASS':'NOT PASSED'):'PRACTICE SCORE'}</div><div class="summary">${S.scores.map((x,i)=>`<div class="summaryRow"><span>Clip ${String(i+1).padStart(2,'0')}</span><b>${x} / 10</b></div>`).join('')}</div><p class="security">Pass benchmark: 60 / 100. Internal training interface — not an official government result.</p><a class="btn primary" href="index.html">RETURN TO HPT HOME</a></section>`;}
function esc(x){return x.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.HPT={start};})();
