-- Additive upgrade for the poster-based sign library. Run after schema.sql.
insert into public.lesson_categories(id,name_en,name_ml,display_order) values
('trafficpolice','Traffic Police Hand Signals','ട്രാഫിക് പോലീസ് കൈ സിഗ്നലുകൾ',6),
('driverhand','Driver Hand Signals','ഡ്രൈവർ കൈ സിഗ്നലുകൾ',7),
('other','Other Important Signs','മറ്റ് പ്രധാന അടയാളങ്ങൾ',8)
on conflict (id) do update set name_en=excluded.name_en,name_ml=excluded.name_ml,display_order=excluded.display_order;

insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_20','mandatory','Circular','Width Limit','വീതി പരിധി','Do not enter or operate a vehicle where the permitted vehicle width is exceeded.','അനുവദിച്ചിരിക്കുന്ന വാഹന വീതി പരിധി കവിയുന്ന വാഹനവുമായി ഈ നിയന്ത്രിത ഭാഗത്തേക്ക് പ്രവേശിക്കരുത്.',24) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_21','mandatory','Circular','Height Limit','ഉയര പരിധി','Do not proceed if the vehicle height exceeds the indicated clearance.','അടയാളപ്പെടുത്തിയ ഉയരപരിധിയേക്കാൾ ഉയരമുള്ള വാഹനവുമായി മുന്നോട്ട് പോകരുത്.',25) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_22','mandatory','Circular','Load Limit','ഭാര പരിധി','Do not exceed the indicated maximum permitted load.','അടയാളപ്പെടുത്തിയ പരമാവധി ഭാരപരിധി കവിയരുത്.',26) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_23','mandatory','Circular','No Vehicles','വാഹനങ്ങൾ പ്രവേശിക്കരുത്','Vehicles are prohibited from entering the restricted road or area.','ഈ നിയന്ത്രിത റോഡിലേക്കോ മേഖലയിലേക്കോ വാഹനങ്ങൾ പ്രവേശിക്കരുത്.',27) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_24','mandatory','Circular','No Motor Cycles','മോട്ടോർ സൈക്കിൾ പാടില്ല','Motor cycles are prohibited in the indicated area.','അടയാളം കാണിക്കുന്ന പ്രദേശത്ത് മോട്ടോർ സൈക്കിളുകൾക്ക് പ്രവേശനമില്ല.',28) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_25','mandatory','Circular','No Cycles','സൈക്കിൾ പാടില്ല','Cycles are prohibited in the indicated area.','അടയാളം കാണിക്കുന്ന പ്രദേശത്ത് സൈക്കിളുകൾക്ക് പ്രവേശനമില്ല.',29) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_26','mandatory','Circular','No Pedestrians','കാൽനടയാത്ര പാടില്ല','Pedestrians must not enter the restricted area.','നിയന്ത്രിത മേഖലയിലേക്ക് കാൽനടയായി പ്രവേശിക്കരുത്.',30) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_27','mandatory','Circular','No Parking or Stopping','പാർക്കിംഗും നിർത്തലും പാടില്ല','Neither parking nor stopping is permitted in the restricted area.','ഈ നിയന്ത്രിത സ്ഥലത്ത് പാർക്ക് ചെയ്യുകയോ വാഹനം നിർത്തുകയോ ചെയ്യരുത്.',31) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_28','mandatory','Circular','End of Speed Limit','വേഗപരിധി അവസാനിക്കുന്നു','The previously posted speed restriction ends here; follow the next applicable limit.','മുമ്പ് ബാധകമായിരുന്ന വേഗപരിധി ഇവിടെ അവസാനിക്കുന്നു. തുടർന്ന് ബാധകമായ വേഗപരിധി പാലിക്കുക.',32) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_29','mandatory','Circular','Compulsory Ahead or Left','മുന്നോട്ടോ ഇടത്തോട്ടോ മാത്രം','Proceed only straight ahead or to the left as indicated.','അടയാളം കാണിക്കുന്നതുപോലെ മുന്നോട്ടോ ഇടത്തോട്ടോ മാത്രമേ പോകാവൂ.',33) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_30','mandatory','Circular','Compulsory Keep Right','വലതുവശം ചേർന്ന് പോകുക','Keep the vehicle to the right side as directed.','അടയാളം നിർദ്ദേശിക്കുന്ന രീതിയിൽ റോഡിന്റെ വലതുവശം ചേർന്ന് വാഹനം ഓടിക്കണം.',34) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_31','mandatory','Circular','Compulsory Ahead or Right','മുന്നോട്ടോ വലത്തോട്ടോ മാത്രം','Proceed only straight ahead or to the right as indicated.','അടയാളം കാണിക്കുന്നതുപോലെ മുന്നോട്ടോ വലത്തോട്ടോ മാത്രമേ പോകാവൂ.',35) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_32','mandatory','Circular','Compulsory Turn Left','നിർബന്ധിത ഇടത് തിരിവ്','Turn left as indicated by the sign.','അടയാളം കാണിക്കുന്ന ദിശയിൽ ഇടത്തോട്ട് തിരിയണം.',36) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('man_33','mandatory','Circular','Compulsory Roundabout','നിർബന്ധിത റൗണ്ടബൗട്ട്','Follow the indicated roundabout direction.','അടയാളം നിർദ്ദേശിക്കുന്ന റൗണ്ടബൗട്ട് ദിശ പാലിക്കുക.',37) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('caut_34','cautionary','Triangular','Double Curve','ഇരട്ട വളവ്','Two successive curves are ahead. Reduce speed and maintain lane position.','തുടർച്ചയായ രണ്ട് വളവുകൾ മുന്നിലുണ്ട്. വേഗത കുറച്ച് സ്വന്തം ലെയിനിൽ തുടരുക.',40) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('caut_35','cautionary','Triangular','Steep Ascent','കുത്തനെയുള്ള കയറ്റം','A steep uphill section is ahead. Select a suitable gear and control speed.','മുന്നിൽ കുത്തനെയുള്ള കയറ്റമാണ്. അനുയോജ്യമായ ഗിയർ തിരഞ്ഞെടുക്കുകയും വേഗത നിയന്ത്രിക്കുകയും ചെയ്യുക.',41) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('caut_36','cautionary','Triangular','Steep Descent','കുത്തനെയുള്ള ഇറക്കം','A steep downhill section is ahead. Reduce speed and use appropriate control.','മുന്നിൽ കുത്തനെയുള്ള ഇറക്കമാണ്. വേഗത കുറച്ച് അനുയോജ്യമായ നിയന്ത്രണം ഉപയോഗിക്കുക.',42) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('caut_37','cautionary','Triangular','Loose Gravel','അയഞ്ഞ കല്ലുകൾ','Loose gravel may reduce tyre grip. Slow down and avoid sudden manoeuvres.','റോഡിൽ അയഞ്ഞ കല്ലുകൾ ഉണ്ടാകാം. വേഗത കുറച്ച് പെട്ടെന്നുള്ള നീക്കങ്ങൾ ഒഴിവാക്കുക.',43) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('caut_38','cautionary','Triangular','Falling Rocks','പാറകൾ വീഴാം','Rocks may fall onto the road. Proceed carefully.','റോഡിലേക്ക് പാറകൾ വീഴാൻ സാധ്യതയുണ്ട്. ശ്രദ്ധയോടെ സഞ്ചരിക്കുക.',44) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('caut_39','cautionary','Triangular','Uneven Road','റോഡ് നിരപ്പല്ല','The road surface may be uneven. Reduce speed and drive carefully.','റോഡ് നിരപ്പല്ലാത്ത ഭാഗം മുന്നിലുണ്ട്. വേഗത കുറച്ച് ശ്രദ്ധയോടെ ഓടിക്കുക.',45) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('caut_40','cautionary','Triangular','Dangerous Dip','അപകടകരമായ താഴ്വര','A sudden dip is ahead. Reduce speed and maintain control.','മുന്നിൽ പെട്ടെന്നുള്ള താഴ്ന്ന ഭാഗമുണ്ട്. വേഗത കുറച്ച് വാഹനം നിയന്ത്രിക്കുക.',46) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('caut_41','cautionary','Triangular','Hump','ഹമ്പ്','A road hump is ahead. Slow down before crossing.','മുന്നിൽ ഹമ്പ് ഉണ്ട്. കടക്കുന്നതിന് മുമ്പ് വേഗത കുറയ്ക്കുക.',47) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('caut_42','cautionary','Triangular','Traffic Signals','ട്രാഫിക് സിഗ്നലുകൾ മുന്നിൽ','Traffic signals are ahead. Slow down and be prepared to stop.','മുന്നിൽ ട്രാഫിക് സിഗ്നലുകൾ ഉണ്ട്. വേഗത കുറച്ച് നിർത്താൻ തയ്യാറാകുക.',48) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('info_11','informatory','Rectangular','Drinking Water','കുടിവെള്ളം','A drinking-water facility is available nearby.','സമീപത്ത് കുടിവെള്ള സൗകര്യം ലഭ്യമാണ്.',60) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('info_12','informatory','Rectangular','Post Office','പോസ്റ്റ് ഓഫീസ്','A post office facility is available nearby.','സമീപത്ത് പോസ്റ്റ് ഓഫീസ് സൗകര്യം ലഭ്യമാണ്.',61) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('info_13','informatory','Rectangular','Tourist Place','വിനോദസഞ്ചാര കേന്ദ്രം','A tourist attraction or facility is nearby.','സമീപത്ത് വിനോദസഞ്ചാര കേന്ദ്രമോ സൗകര്യമോ ഉണ്ട്.',62) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('info_14','informatory','Rectangular','Information','വിവര കേന്ദ്രം','Information facilities are available nearby.','സമീപത്ത് വിവരസൗകര്യം ലഭ്യമാണ്.',63) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('info_15','informatory','Rectangular','Police','പോലീസ്','Police assistance or a police facility is nearby.','സമീപത്ത് പോലീസ് സഹായമോ പോലീസ് സ്റ്റേഷനോ ഉണ്ട്.',64) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('info_16','informatory','Rectangular','Workshop','വർക്ക്ഷോപ്പ്','A vehicle repair workshop is available nearby.','സമീപത്ത് വാഹന റിപ്പയർ വർക്ക്ഷോപ്പ് ലഭ്യമാണ്.',65) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('other_01','other','Marker','Hazard Marker','അപകട സൂചക മാർക്കർ','Refer to the sign and follow the applicable traffic instruction.','അടയാളത്തിന്റെ നിർദ്ദേശം പാലിച്ച് സുരക്ഷിതമായി വാഹനം ഓടിക്കുക.',70) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('other_02','other','Marker','Object Marker','തടസ്സ സൂചക മാർക്കർ','Refer to the sign and follow the applicable traffic instruction.','അടയാളത്തിന്റെ നിർദ്ദേശം പാലിച്ച് സുരക്ഷിതമായി വാഹനം ഓടിക്കുക.',71) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('other_03','other','Marker','End of Restriction','നിയന്ത്രണം അവസാനിക്കുന്നു','Refer to the sign and follow the applicable traffic instruction.','അടയാളത്തിന്റെ നിർദ്ദേശം പാലിച്ച് സുരക്ഷിതമായി വാഹനം ഓടിക്കുക.',72) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('other_04','other','Marker','Go','പോകുക','Refer to the sign and follow the applicable traffic instruction.','അടയാളത്തിന്റെ നിർദ്ദേശം പാലിച്ച് സുരക്ഷിതമായി വാഹനം ഓടിക്കുക.',73) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('other_05','other','Marker','Stop','നിർത്തുക','Refer to the sign and follow the applicable traffic instruction.','അടയാളത്തിന്റെ നിർദ്ദേശം പാലിച്ച് സുരക്ഷിതമായി വാഹനം ഓടിക്കുക.',74) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('other_06','other','Marker','Kilometre Stone','കിലോമീറ്റർ കല്ല്','Refer to the sign and follow the applicable traffic instruction.','അടയാളത്തിന്റെ നിർദ്ദേശം പാലിച്ച് സുരക്ഷിതമായി വാഹനം ഓടിക്കുക.',75) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('police_01','trafficpolice','Police Hand Signal','Stop','നിർത്തുക','Right arm raised vertically with palm forward.','പോലീസ് ഉദ്യോഗസ്ഥന്റെ കൈസിഗ്നൽ ശ്രദ്ധിച്ച് അതനുസരിച്ച് വാഹനം നിയന്ത്രിക്കുക.',80) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('police_02','trafficpolice','Police Hand Signal','Move Forward','മുന്നോട്ട് പോകുക','Right arm moved up and down to invite traffic forward.','പോലീസ് ഉദ്യോഗസ്ഥന്റെ കൈസിഗ്നൽ ശ്രദ്ധിച്ച് അതനുസരിച്ച് വാഹനം നിയന്ത്രിക്കുക.',81) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('police_03','trafficpolice','Police Hand Signal','Slow Down','വേഗത കുറയ്ക്കുക','Right arm moved horizontally with palm down.','പോലീസ് ഉദ്യോഗസ്ഥന്റെ കൈസിഗ്നൽ ശ്രദ്ധിച്ച് അതനുസരിച്ച് വാഹനം നിയന്ത്രിക്കുക.',82) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('police_04','trafficpolice','Police Hand Signal','Turn Left','ഇടത്തോട്ട് തിരിയുക','Right arm horizontal and moved from right to left.','പോലീസ് ഉദ്യോഗസ്ഥന്റെ കൈസിഗ്നൽ ശ്രദ്ധിച്ച് അതനുസരിച്ച് വാഹനം നിയന്ത്രിക്കുക.',83) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('police_05','trafficpolice','Police Hand Signal','Turn Right','വലത്തോട്ട് തിരിയുക','Right arm horizontal and moved from left to right.','പോലീസ് ഉദ്യോഗസ്ഥന്റെ കൈസിഗ്നൽ ശ്രദ്ധിച്ച് അതനുസരിച്ച് വാഹനം നിയന്ത്രിക്കുക.',84) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('police_06','trafficpolice','Police Hand Signal','Attention','ശ്രദ്ധിക്കുക','Right arm raised with whistle / attention signal.','പോലീസ് ഉദ്യോഗസ്ഥന്റെ കൈസിഗ്നൽ ശ്രദ്ധിച്ച് അതനുസരിച്ച് വാഹനം നിയന്ത്രിക്കുക.',85) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('driver_01','driverhand','Driver Hand Signal','Intend to Move Left','ഇടത്തോട്ട് പോകാനുള്ള സൂചന','Arm signal indicating an intention to move left.','ഡ്രൈവർ കൈസിഗ്നൽ വ്യക്തമായി നൽകി മറ്റ് റോഡ് ഉപയോക്താക്കൾക്ക് ഉദ്ദേശ്യം അറിയിക്കുക.',90) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('driver_02','driverhand','Driver Hand Signal','Intend to Move Right','വലത്തോട്ട് പോകാനുള്ള സൂചന','Arm signal indicating an intention to move right.','ഡ്രൈവർ കൈസിഗ്നൽ വ്യക്തമായി നൽകി മറ്റ് റോഡ് ഉപയോക്താക്കൾക്ക് ഉദ്ദേശ്യം അറിയിക്കുക.',91) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('driver_03','driverhand','Driver Hand Signal','Intend to Stop','നിർത്താനുള്ള സൂചന','Arm signal indicating an intention to stop.','ഡ്രൈവർ കൈസിഗ്നൽ വ്യക്തമായി നൽകി മറ്റ് റോഡ് ഉപയോക്താക്കൾക്ക് ഉദ്ദേശ്യം അറിയിക്കുക.',92) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('driver_04','driverhand','Driver Hand Signal','Intend to Slow Down','വേഗത കുറയ്ക്കാനുള്ള സൂചന','Arm signal indicating an intention to slow down.','ഡ്രൈവർ കൈസിഗ്നൽ വ്യക്തമായി നൽകി മറ്റ് റോഡ് ഉപയോക്താക്കൾക്ക് ഉദ്ദേശ്യം അറിയിക്കുക.',93) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('driver_05','driverhand','Driver Hand Signal','Indicating Overtaking','ഓവർടേക്ക് ചെയ്യാനുള്ള സൂചന','Arm signal indicating that the vehicle is about to overtake.','ഡ്രൈവർ കൈസിഗ്നൽ വ്യക്തമായി നൽകി മറ്റ് റോഡ് ഉപയോക്താക്കൾക്ക് ഉദ്ദേശ്യം അറിയിക്കുക.',94) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('rm_05','roadmarking','Road Marking','Edge Line (White)','വെള്ള അരികുരേഖ','Follow the road marking and associated traffic control.','വെള്ള അരികുരേഖ കാണുന്നിടത്ത് ബന്ധപ്പെട്ട റോഡ് നിയന്ത്രണം പാലിക്കുക.',54) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('rm_06','roadmarking','Road Marking','No Overtaking Double White Line','ഓവർടേക്ക് പാടില്ലാത്ത ഇരട്ട വെള്ളരേഖ','Follow the road marking and associated traffic control.','ഓവർടേക്ക് പാടില്ലാത്ത ഇരട്ട വെള്ളരേഖ കാണുന്നിടത്ത് ബന്ധപ്പെട്ട റോഡ് നിയന്ത്രണം പാലിക്കുക.',55) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('rm_07','roadmarking','Road Marking','Give Way Line (Broken White)','വഴി കൊടുക്കേണ്ട തകർന്ന വെള്ളരേഖ','Follow the road marking and associated traffic control.','വഴി കൊടുക്കേണ്ട തകർന്ന വെള്ളരേഖ കാണുന്നിടത്ത് ബന്ധപ്പെട്ട റോഡ് നിയന്ത്രണം പാലിക്കുക.',56) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('rm_08','roadmarking','Road Marking','Yellow Box','മഞ്ഞ ബോക്സ് മാർക്കിംഗ്','Follow the road marking and associated traffic control.','മഞ്ഞ ബോക്സ് മാർക്കിംഗ് കാണുന്നിടത്ത് ബന്ധപ്പെട്ട റോഡ് നിയന്ത്രണം പാലിക്കുക.',57) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('rm_09','roadmarking','Road Marking','Direction Arrows','ദിശാ അമ്പുകൾ','Follow the road marking and associated traffic control.','ദിശാ അമ്പുകൾ കാണുന്നിടത്ത് ബന്ധപ്പെട്ട റോഡ് നിയന്ത്രണം പാലിക്കുക.',58) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('rm_10','roadmarking','Road Marking','Lane Markings','ലെയിൻ മാർക്കിംഗുകൾ','Follow the road marking and associated traffic control.','ലെയിൻ മാർക്കിംഗുകൾ കാണുന്നിടത്ത് ബന്ധപ്പെട്ട റോഡ് നിയന്ത്രണം പാലിക്കുക.',59) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('rm_11','roadmarking','Road Marking','Pedestrian Path','കാൽനട പാത','Follow the road marking and associated traffic control.','കാൽനട പാത കാണുന്നിടത്ത് ബന്ധപ്പെട്ട റോഡ് നിയന്ത്രണം പാലിക്കുക.',60) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('rm_12','roadmarking','Road Marking','Speed Breaker Markings','സ്പീഡ് ബ്രേക്കർ മാർക്കിംഗ്','Follow the road marking and associated traffic control.','സ്പീഡ് ബ്രേക്കർ മാർക്കിംഗ് കാണുന്നിടത്ത് ബന്ധപ്പെട്ട റോഡ് നിയന്ത്രണം പാലിക്കുക.',61) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
insert into public.lesson_signs(sign_id,category_id,shape,title_en,title_ml,rule_en,rule_ml,display_order) values ('rm_13','roadmarking','Road Marking','No Parking (Yellow Line)','പാർക്കിംഗ് പാടില്ല — മഞ്ഞ രേഖ','Follow the road marking and associated traffic control.','പാർക്കിംഗ് പാടില്ല — മഞ്ഞ രേഖ കാണുന്നിടത്ത് ബന്ധപ്പെട്ട റോഡ് നിയന്ത്രണം പാലിക്കുക.',62) on conflict (sign_id) do update set category_id=excluded.category_id,shape=excluded.shape,title_en=excluded.title_en,title_ml=excluded.title_ml,rule_en=excluded.rule_en,rule_ml=excluded.rule_ml,display_order=excluded.display_order;
